openapi: 3.1.0
info:
  title: Authorisation API v2
  description: |
    The Authorisation API is a core EBSI service responsible to issue Short Term
    Access Tokens (JWS) to the EBSI Platform for entities (Natural Persons,
    Legal Entities) and trusted Applications (EBSI or third-party applications)
    in exchange of their presentation of a long term EBSI Verifiable
    Authorisation credential, plus their authentication/identification. Access
    tokens are required by entities and applications to access the protected
    resources of EBSI.

    Users receive access tokens after they present a valid EBSI Verifiable
    Authorisation credential and prove ownership over their DID.

    Trusted Applications receive access tokens if they are well registered in
    the Trusted Apps Registry (application public keys are listed), are
    authorised there to access the requested protected resources, and
    successfully prove their private key ownership. We implement the
    Authenticated Key Exchange cryptographic identification protocol.
  version: 2.0.0
  contact:
    name: EBSI Support - Service Desk
    url: https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/11
  license:
    name: EUPL-1.2
    url: https://joinup.ec.europa.eu/page/eupl-text-11-12
servers:
  - url: http://localhost
    description: Local Computer Environment
  - url: https://api-test.ebsi.eu
    description: EBSI Test Environment
  - url: https://api-pilot.ebsi.eu
    description: EBSI Pilot Environment
  - url: https://api-conformance.ebsi.eu
    description: EBSI Conformance Environment
paths:
  /authorisation/v2/authentication-requests:
    post:
      operationId: post-authentication-requests
      tags:
        - Endpoints
      summary: Initiate a SIOP DID Auth request
      description: Natural Person and Legal Entities entry point to initiate a SIOP DID Auth Request.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AuthenticationRequest"
            examples:
              OIDC SIOP Authentication Request:
                description: |
                  EBSI supports OIDC and OAuth2 authentication, hence the scope MUST a valid EBSI authentication scope.
                  The endpoint returns an OIDC SIOP V2 authentication request as URI string.
                value:
                  scope: openid did_authn
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthenticationRequestResponse"
              examples:
                Authentication Request:
                  value:
                    uri: "openid://?response_type=id_token&client_id=https%3A%2F%2Fapi-pilot.ebsi.eu%2Fauthorisation%2Fv2%2Fsiop-sessions&scope=openid+did_authn&nonce=09e8ebfe-674e-4e4c-82b3-da153f8625c2&request=eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJraWQiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3RydXN0ZWQtYXBwcy1yZWdpc3RyeS92My9hcHBzL2F1dGhvcmlzYXRpb24tYXBpX3BpbG90LXRlbXAtMDEifQ.eyJzY29wZSI6Im9wZW5pZCBkaWRfYXV0aG4iLCJyZXNwb25zZV90eXBlIjoiaWRfdG9rZW4iLCJyZXNwb25zZV9tb2RlIjoicG9zdCIsImNsaWVudF9pZCI6Imh0dHBzOi8vYXBpLXBpbG90LmVic2kuZXUvYXV0aG9yaXNhdGlvbi92Mi9zaW9wLXNlc3Npb25zIiwicmVkaXJlY3RfdXJpIjoiaHR0cHM6Ly9hcGktcGlsb3QuZWJzaS5ldS9hdXRob3Jpc2F0aW9uL3YyL3Npb3Atc2Vzc2lvbnMiLCJub25jZSI6IjA5ZThlYmZlLTY3NGUtNGU0Yy04MmIzLWRhMTUzZjg2MjVjMiIsImNsYWltcyI6eyJpZF90b2tlbiI6eyJ2ZXJpZmllZF9jbGFpbXMiOnsidmVyaWZpY2F0aW9uIjp7InRydXN0X2ZyYW1ld29yayI6IkVCU0kiLCJldmlkZW5jZSI6eyJ0eXBlIjp7InZhbHVlIjoidmVyaWZpYWJsZV9jcmVkZW50aWFsIn0sImRvY3VtZW50Ijp7InR5cGUiOnsiZXNzZW50aWFsIjp0cnVlLCJ2YWx1ZSI6WyJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsIlZlcmlmaWFibGVBdXRob3Jpc2F0aW9uIl19LCJjcmVkZW50aWFsU2NoZW1hIjp7ImlkIjp7ImVzc2VudGlhbCI6dHJ1ZSwidmFsdWUiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3RydXN0ZWQtc2NoZW1hcy1yZWdpc3RyeS92Mi9zY2hlbWFzL3pITXA1MkxxSldvY21oQTlSa3puVFd1RWVjSlhvUERLdzNrV1FwODFZWTlwQyJ9fX19fX19fSwiaWF0IjoxNjcyODQxODgxLCJpc3MiOiJhdXRob3Jpc2F0aW9uLWFwaV9waWxvdC10ZW1wLTAxIiwiZXhwIjoxNjcyODQyMTgxfQ.Z8jVzKtcTtSD1kBlYin_1jnfZ6BhhYdo18lUSf5xz0RFtkoPonsQyKsS7u72w7fV3oxWUs8YV7QAynGyUxuR_w"
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
  /authorisation/v2/siop-sessions:
    post:
      operationId: post-siop-sessions
      summary: Create a SIOP Session
      description: Sessions Token endpoint as the callback for DID SIOP Response.
      tags:
        - Endpoints
      requestBody:
        description: |
          The request body must contain an ID Token (parameter name: `id_token`) and, optionally, a VP token (as `vp_token`) (only for onboarding).

          The ID Token should be a JWT.
          Its header must contain the signer's `kid` (e.g. `"kid": "did:ebsi:zbM8cCuoBMFNLeQyLiVFyxw#keys-1"`).
          The ID Token payload must contain the following fields:
          - `aud`: the URL of the /siop-sessions endpoint, e.g. "https://api-pilot.ebsi.eu/authorisation/v2/siop-sessions"
          - `sub`: the subject
          - `sub_jwk`: the JWK used to sign the JWT
          - `nonce`: a random UUID
          - `claims`:
            - `encryption_key`: public key used to encrypt the response
          - `responseMode`: should be "form_post",
          - `iss`: should be "https://self-issued.me/v2",
          - `_vp_token`: only if the request also contains a VP token.
            - `presentation_submission`: a VP submission object (https://identity.foundation/presentation-exchange/spec/v2.0.0/#presentation-submission).

          Here's an example of a valid `presentation_submission`:

          ```json
            "presentation_submission": {
              "id": "237b0eec-0b7e-4a16-b3bc-bdd42f57b86b",
              "definition_id": "b5c07e84-55f6-48e1-a531-3608d26fc336",
              "descriptor_map": [
                {
                  "id": "6f43bcea-da4b-4e45-ac2c-25307d6dfe34",
                  "format": "jwt_vp",
                  "path": "$",
                  "path_nested": {
                    "id": "onboarding-input-id",
                    "format": "jwt_vc",
                    "path": "$.vp.verifiableCredential[0]"
                  }
                }
              ]
            }
          ```

          With the associated `vp_token` being a Verifiable Presentation JWT:

          ```
          eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJraWQiOiJkaWQ6ZWJzaTp6c3ROc2VtaWZrd2ZVY2pBYzJucDFXcCNTLTJiQV9lUXNTa1JDbmw0ZnNielVWZGtwM3F4WEVrcnFKTTI3WWhBZUtzIn0.eyJqdGkiOiIiLCJzdWIiOiJkaWQ6ZWJzaTp6c3ROc2VtaWZrd2ZVY2pBYzJucDFXcCIsImlzcyI6ImRpZDplYnNpOnpzdE5zZW1pZmt3ZlVjakFjMm5wMVdwIiwibmJmIjoxNjcyODQyOTc3LCJleHAiOjE2ODg1Njc3NzcsImlhdCI6MTY3Mjg0Mjk3OCwiYXVkIjoiYXV0aG9yaXNhdGlvbi1hcGkiLCJ2cCI6eyJAY29udGV4dCI6WyJodHRwczovL3d3dy53My5vcmcvMjAxOC9jcmVkZW50aWFscy92MSJdLCJ0eXBlIjpbIlZlcmlmaWFibGVQcmVzZW50YXRpb24iXSwidmVyaWZpYWJsZUNyZWRlbnRpYWwiOlsiZXlKaGJHY2lPaUpGVXpJMU5rc2lMQ0owZVhBaU9pSktWMVFpTENKcmFXUWlPaUprYVdRNlpXSnphVHA2Y2pKeVYwUklTSEpWUTJSYVFWYzNkM05UWWpWdVVTTnJaWGx6TFRFaWZRLmV5SnFkR2tpT2lKMll6cGxZbk5wT21GMWRHaGxiblJwWTJGMGFXOXVJMk00TUdSalpHTmlMV1UxTURVdE5HTTRNQzFoTlRnekxUTTROakZsT0RObFlUQTRZaUlzSW5OMVlpSTZJbVJwWkRwbFluTnBPbnB6ZEU1elpXMXBabXQzWmxWamFrRmpNbTV3TVZkd0lpd2lhWE56SWpvaVpHbGtPbVZpYzJrNmVuSXljbGRFU0VoeVZVTmtXa0ZYTjNkelUySTFibEVpTENKdVltWWlPakUyTnpJNE5ESTVOemNzSW1WNGNDSTZNVFk0T0RVMk56YzNOeXdpYVdGMElqb3hOamN5T0RReU9UYzNMQ0oyWXlJNmV5SkFZMjl1ZEdWNGRDSTZXeUpvZEhSd2N6b3ZMM2QzZHk1M015NXZjbWN2TWpBeE9DOWpjbVZrWlc1MGFXRnNjeTkyTVNKZExDSnBaQ0k2SW5aak9tVmljMms2WVhWMGFHVnVkR2xqWVhScGIyNGpZemd3WkdOa1kySXRaVFV3TlMwMFl6Z3dMV0UxT0RNdE16ZzJNV1U0TTJWaE1EaGlJaXdpZEhsd1pTSTZXeUpXWlhKcFptbGhZbXhsUTNKbFpHVnVkR2xoYkNJc0lsWmxjbWxtYVdGaWJHVkJkWFJvYjNKcGMyRjBhVzl1SWwwc0ltbHpjM1ZsY2lJNkltUnBaRHBsWW5OcE9ucHlNbkpYUkVoSWNsVkRaRnBCVnpkM2MxTmlOVzVSSWl3aWFYTnpkV0Z1WTJWRVlYUmxJam9pTWpBeU15MHdNUzB3TkZReE5Eb3pOam94TjFvaUxDSnBjM04xWldRaU9pSXlNREl6TFRBeExUQTBWREUwT2pNMk9qRTNXaUlzSW5aaGJHbGtSbkp2YlNJNklqSXdNak10TURFdE1EUlVNVFE2TXpZNk1UZGFJaXdpWlhod2FYSmhkR2x2YmtSaGRHVWlPaUl5TURJekxUQTNMVEExVkRFME9qTTJPakUzV2lJc0ltTnlaV1JsYm5ScFlXeFRkV0pxWldOMElqcDdJbWxrSWpvaVpHbGtPbVZpYzJrNmVuTjBUbk5sYldsbWEzZG1WV05xUVdNeWJuQXhWM0FpZlN3aVkzSmxaR1Z1ZEdsaGJGTmphR1Z0WVNJNmV5SnBaQ0k2SW1oMGRIQnpPaTh2WVhCcExYQnBiRzkwTG1WaWMya3VaWFV2ZEhKMWMzUmxaQzF6WTJobGJXRnpMWEpsWjJsemRISjVMM1l5TDNOamFHVnRZWE12ZWtoTmNEVXlUSEZLVjI5amJXaEJPVkpyZW01VVYzVkZaV05LV0c5UVJFdDNNMnRYVVhBNE1WbFpPWEJESWl3aWRIbHdaU0k2SWtaMWJHeEtjMjl1VTJOb1pXMWhWbUZzYVdSaGRHOXlNakF5TVNKOWZYMC5vdmR1a20wVnpRNWpUZE9nTmJHY0g4LTVCdFZTMTNqcDhxUUstV0JJQTlvbmU5WmswUnRXZWV2RkJMQ05LeGdCWS0tMk1WZ0E2eUJTNHR4Y3Z4VlZhZyJdLCJob2xkZXIiOiJkaWQ6ZWJzaTp6c3ROc2VtaWZrd2ZVY2pBYzJucDFXcCJ9fQ.86g3f_b5JvsvKwuayWGp_9BpQ0GwsvmY_51K88npaFM2CWJH6D3Aqjee4_URXHPtdSzKoiBhPdGqGyz3RACsKQ
          ```
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: "#/components/schemas/SiopSessionsRequest"
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ake1SiopResponse"
              examples:
                Encrypted access token:
                  value:
                    ake1_enc_payload: ce527bf1e06bd6241625d54e76bdb5ac029c455f97324ed20a5038724966ba5d9befd49195b4841b513c7f23e785c99f87bad2e255cbceb1152cef05b15137a1411520d8d578961f16d6c59ec042889e45cb4d3965d9d859dac8f217b3b3776ad342a605f2bb985d820ad8b0f6cb2c7c40da4d1ebd3efb5a3d57507e0479801c088e68b277fac799f852c1053a1dacc7cdb921cff2006eaf1b3fa3a5b64de91e991390b7317814625f490a1354dc2b69498b2bfad7caf0e819ebd93cccb2ef26e399d996ab19910605d798dacf9f78489dd7bac8613b5da28314e1153d929a9059decedce00eeb2848ee95f14e523f9f12372e71b9db4ebe702ce508d2dbc1e5cbdafcd5a15afe397fb35f9a45424c6aac43380b054185cbac4f498a5db4dcf517cf8bc760354c26e2e1af37dbdf06f888e5d424a66ab9546475b187787b557d197af20c7ac1e0639acf0304f051194da4be7c8badb0747b3e669ffd7ffe5a2c9c2060f338d8e4eb3010e10e6a67a1c8fe21d48ee7bc5d540497071f80dd36e58d309e868837c193dd5646b33baa61c3c190d5ce44d08bc6820d240e14edd12af9ae8242e5a7186c1697426d14e97101313331cb1d803030cd2d6d2799852bda0dbc80b3c927efffc19d170327ac11c5d645b83c38fdcfb9ac779d9eac795d8eb671fe0ade56cdcb020261e1bf6d2e1d2fdfc1f954959c2d5516adf3f2abcee298c92b5451e3dee89d1903b8390fe9a426278ec879a59e682eabf8b8f3ad4482de9c636a41e506c82d7d0be1a92d926ba7fb05779f2612a86f8b47e10477b1d6080044d1f983cf3cb81e35af5b3ea4205e1d25ce0b6d20755442904d670380082203e25d4326df0ab47ee8bb404f98d5184a3949e043a0656e856f78f442fb33a2ec63c7347520c796fb721bfc0c6106c0db9e0580ba17aa3f96abf1a4744256635803f90bcfce185ddba20a8635a1c59f68760220ddaf296ac3a582ea953f928290c50f186ea8909a9a94a82b6b1c8204f243a4ed4cef5fd672959cec8359a57ac08c4b41ccb515b963f675af7cf4a9bef97f13942a63678680fb8f9e2de766f3c578d6f5913d7e71aafbd5ebc965b90ce4c3dc4a7bc2af74754c3e7c05fc3fbd1851ee5caa4723fe7bf5a9cd804a979bbd341836bcb3e82ad164748cb46f5d9fd4b599d27a307962eea6465eb91a6155
                    ake1_sig_payload:
                      iat: 1672841881
                      exp: 1672842781
                      ake1_nonce: 53a6e914-ef94-412b-b226-82da24be3dd9
                      ake1_enc_payload: ce527bf1e06bd6241625d54e76bdb5ac029c455f97324ed20a5038724966ba5d9befd49195b4841b513c7f23e785c99f87bad2e255cbceb1152cef05b15137a1411520d8d578961f16d6c59ec042889e45cb4d3965d9d859dac8f217b3b3776ad342a605f2bb985d820ad8b0f6cb2c7c40da4d1ebd3efb5a3d57507e0479801c088e68b277fac799f852c1053a1dacc7cdb921cff2006eaf1b3fa3a5b64de91e991390b7317814625f490a1354dc2b69498b2bfad7caf0e819ebd93cccb2ef26e399d996ab19910605d798dacf9f78489dd7bac8613b5da28314e1153d929a9059decedce00eeb2848ee95f14e523f9f12372e71b9db4ebe702ce508d2dbc1e5cbdafcd5a15afe397fb35f9a45424c6aac43380b054185cbac4f498a5db4dcf517cf8bc760354c26e2e1af37dbdf06f888e5d424a66ab9546475b187787b557d197af20c7ac1e0639acf0304f051194da4be7c8badb0747b3e669ffd7ffe5a2c9c2060f338d8e4eb3010e10e6a67a1c8fe21d48ee7bc5d540497071f80dd36e58d309e868837c193dd5646b33baa61c3c190d5ce44d08bc6820d240e14edd12af9ae8242e5a7186c1697426d14e97101313331cb1d803030cd2d6d2799852bda0dbc80b3c927efffc19d170327ac11c5d645b83c38fdcfb9ac779d9eac795d8eb671fe0ade56cdcb020261e1bf6d2e1d2fdfc1f954959c2d5516adf3f2abcee298c92b5451e3dee89d1903b8390fe9a426278ec879a59e682eabf8b8f3ad4482de9c636a41e506c82d7d0be1a92d926ba7fb05779f2612a86f8b47e10477b1d6080044d1f983cf3cb81e35af5b3ea4205e1d25ce0b6d20755442904d670380082203e25d4326df0ab47ee8bb404f98d5184a3949e043a0656e856f78f442fb33a2ec63c7347520c796fb721bfc0c6106c0db9e0580ba17aa3f96abf1a4744256635803f90bcfce185ddba20a8635a1c59f68760220ddaf296ac3a582ea953f928290c50f186ea8909a9a94a82b6b1c8204f243a4ed4cef5fd672959cec8359a57ac08c4b41ccb515b963f675af7cf4a9bef97f13942a63678680fb8f9e2de766f3c578d6f5913d7e71aafbd5ebc965b90ce4c3dc4a7bc2af74754c3e7c05fc3fbd1851ee5caa4723fe7bf5a9cd804a979bbd341836bcb3e82ad164748cb46f5d9fd4b599d27a307962eea6465eb91a6155
                      did: did:ebsi:zbM8cCuoBMFNLeQyLiVFyxw
                      iss: authorisation-api_pilot-temp-01
                    ake1_jws_detached: eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJraWQiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3RydXN0ZWQtYXBwcy1yZWdpc3RyeS92My9hcHBzL2F1dGhvcmlzYXRpb24tYXBpX3BpbG90LXRlbXAtMDEifQ..bJ5gwcsgYcRTpMAJYpkUPGSYA962eioQ94Yju7buVGneuCCmelxWH-ZhKxMf7RolebgdVrrnNIIhdTZLJ8NpMw
                    kid: https://api-pilot.ebsi.eu/trusted-apps-registry/v3/apps/authorisation-api_pilot-temp-01
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
  /authorisation/v2/oauth2-sessions:
    post:
      operationId: post-oauth2-sessions
      summary: Create an OAuth2 Session
      description: Session Token endpoint for Component Authorisation (DID Auth - CCG Flow).
      tags:
        - Endpoints
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OAuth2SessionsRequest"
            examples:
              OAuth2 Session Request:
                value:
                  grantType: client_credentials
                  clientAssertionType: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
                  clientAssertion: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksiLCJraWQiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3RydXN0ZWQtYXBwcy1yZWdpc3RyeS92My9hcHBzL3Rlc3QtYXBwLXBpbG90MiJ9.eyJpYXQiOjE2NzI4NDUxOTYsImV4cCI6MTY3Mjg0NTIxMSwianRpIjoiZDQwNzdmMzctNzMxYy00Y2M0LThmYmItZDE0MWE5MjUyODViIiwiYXVkIjoibGVkZ2VyLWFwaSIsInN1YiI6InRlc3QtYXBwLXBpbG90MiIsIm5vbmNlIjoiOWEzNTQxODQtMzlmMy00MGJiLTg1NDctMjc5N2YzZDhlNThhIiwiaXNzIjoidGVzdC1hcHAtcGlsb3QyIn0.enmQemuwwkBSPTokpUjacOSgjM4JIo6OnHLaOiw_A3lwwJqGssBjHOfrxEIVOBCvdtLOSFDa6he8qCnqGef95Q
                  scope: openid did_authn
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Ake1OAuth2Response"
              examples:
                OAuth2 response:
                  value:
                    ake1_enc_payload: a5c94fe3c30baec627ab0afb26cf4b5f0319f3eb08752991fb98149e16549a2be069461ce0de3b83f3066027da8565d4516d043c1572b837a0263ffe493c5ded124bf4aaf060e87006e21d4b658abf43b6953f1f23ff982acc74d2c341545f976c5052e07730b304aa6bd37bbc8f54535c6ff84fffcf6caadb1757a854c8d559000bd1fb255e83b2e6a79e5a23a7b67c429ffa4a3e1a7acdc18c4cc7b623584a2ce612ae8052ecc42e116a0664c85c0c30f366c9a42d8d3ffc76e0da3b2c16e0cf19a90086d9c0f9db05218197f8bf07060d27b5c6caac3afdb90b4292123f80df6dbd7922b975335f408b74671790413e02c30d9db9ca96cb9bc25a9e51853f408bd565cadfaaf06526799deb2be248d67c82aaf13010dddaa40dbffe2e0e1fb5689ccbca3785707e188d2cf10f320aca678ff48491d4dec3227e2c17c9843fd8283ce79a3ee212c81063248507dbb694c11eb893235e0b6dc69e78eb69c4fc85ecaa91c8c72c43fd5362fe1f382f57f4dd7b0ee03a5542c83602a437e4b03fb434f6a44e4a04f0adbf30abacdaa69a5b826c77ac3faa27a650f3bcff21cdd1f6793df3dad9bae33496c9da4acba4c8fd793bc23f0d9032d416e753cd802153dc0ea3925d1110367322cba5450ceceb3cd3d4228228177dd8d667eda5691030183e0d3f1be40ac793d1d42af344895d85fb84d9374a344e8f95a33b1c740fa4c84ee016765a63fceda74d5decbf5ee76df9119c73491449a70554541900348b306ab07111312d2b74c226df7f194be00b8335a207bd41399487bd4216edf078a11b8a8b9b93d50e2cb673ccbce0b97d994b54b97068ef317e1136193b17d34764e6ec9c68be69b42aaf1aa1c9bb448dd38eb3a96957fc0a5b81c4710921c6605da420614042518739a02f8ed44338236733a5b2964a3bba2e4333034cb14746e6c2692445c65e8ec124c8e49413d01d86cd1b3dbd863807dc1d9a408e47c46c02f3e7bacbcbc387b03ebd26be6bd1d6f70f5c308081a8ca66beaea71ffee9d1cc375fc299323c938f5c200a2f031380f5347d1604d57a4af3c35a4891e5b1e2bb8573e36a4e1af5fbe62e1b188d119a6b07b25bda8086f3f0aa2139ee4e7144cd
                    ake1_sig_payload:
                      iat: 1672845197
                      exp: 1672846097
                      ake1_nonce: 9a354184-39f3-40bb-8547-2797f3d8e58a
                      ake1_enc_payload: a5c94fe3c30baec627ab0afb26cf4b5f0319f3eb08752991fb98149e16549a2be069461ce0de3b83f3066027da8565d4516d043c1572b837a0263ffe493c5ded124bf4aaf060e87006e21d4b658abf43b6953f1f23ff982acc74d2c341545f976c5052e07730b304aa6bd37bbc8f54535c6ff84fffcf6caadb1757a854c8d559000bd1fb255e83b2e6a79e5a23a7b67c429ffa4a3e1a7acdc18c4cc7b623584a2ce612ae8052ecc42e116a0664c85c0c30f366c9a42d8d3ffc76e0da3b2c16e0cf19a90086d9c0f9db05218197f8bf07060d27b5c6caac3afdb90b4292123f80df6dbd7922b975335f408b74671790413e02c30d9db9ca96cb9bc25a9e51853f408bd565cadfaaf06526799deb2be248d67c82aaf13010dddaa40dbffe2e0e1fb5689ccbca3785707e188d2cf10f320aca678ff48491d4dec3227e2c17c9843fd8283ce79a3ee212c81063248507dbb694c11eb893235e0b6dc69e78eb69c4fc85ecaa91c8c72c43fd5362fe1f382f57f4dd7b0ee03a5542c83602a437e4b03fb434f6a44e4a04f0adbf30abacdaa69a5b826c77ac3faa27a650f3bcff21cdd1f6793df3dad9bae33496c9da4acba4c8fd793bc23f0d9032d416e753cd802153dc0ea3925d1110367322cba5450ceceb3cd3d4228228177dd8d667eda5691030183e0d3f1be40ac793d1d42af344895d85fb84d9374a344e8f95a33b1c740fa4c84ee016765a63fceda74d5decbf5ee76df9119c73491449a70554541900348b306ab07111312d2b74c226df7f194be00b8335a207bd41399487bd4216edf078a11b8a8b9b93d50e2cb673ccbce0b97d994b54b97068ef317e1136193b17d34764e6ec9c68be69b42aaf1aa1c9bb448dd38eb3a96957fc0a5b81c4710921c6605da420614042518739a02f8ed44338236733a5b2964a3bba2e4333034cb14746e6c2692445c65e8ec124c8e49413d01d86cd1b3dbd863807dc1d9a408e47c46c02f3e7bacbcbc387b03ebd26be6bd1d6f70f5c308081a8ca66beaea71ffee9d1cc375fc299323c938f5c200a2f031380f5347d1604d57a4af3c35a4891e5b1e2bb8573e36a4e1af5fbe62e1b188d119a6b07b25bda8086f3f0aa2139ee4e7144cd
                      kid: https://api-pilot.ebsi.eu/trusted-apps-registry/v3/apps/test-app-pilot2
                      iss: authorisation-api_pilot-temp-01
                    ake1_jws_detached: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksiLCJraWQiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3RydXN0ZWQtYXBwcy1yZWdpc3RyeS92My9hcHBzL2F1dGhvcmlzYXRpb24tYXBpX3BpbG90LXRlbXAtMDEifQ..PHbuIxA7oSp8-6oh7BED0fEiFL8gItKETlFzaiuFIKH0aF3RRjJQv-CKc5kEfmhGSO8_46yD2qFXZnsTrHAJFg
                    kid: https://api-pilot.ebsi.eu/trusted-apps-registry/v3/apps/authorisation-api_pilot-temp-01
        "400":
          $ref: "#/components/responses/400"
        "500":
          $ref: "#/components/responses/500"
components:
  schemas:
    ProblemDetails:
      title: Problem Details
      description: A [Problem Details](https://datatracker.ietf.org/doc/html/rfc7807) object.
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide
            human-readable documentation for the problem type.
          default: "about:blank"
        title:
          type: string
          description: A short summary of the problem type.
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem.
          example: Connection timeout
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem. It may or may
            not yield further information if dereferenced.
    AuthenticationRequest:
      title: SIOP Authentication Request
      description: Request to initiate a SIOP authentication process.
      type: object
      properties:
        scope:
          type: string
          description: Scope is used to define the authentication response method.
          example: openid did_authn
      required:
        - scope
    AuthenticationRequestResponse:
      title: SIOP Authentication Request Response
      type: object
      properties:
        uri:
          description: OpenId DID SIOP Uri response.
          type: string
          example: "openid://?response_type=id_token&client_id=https%3A%2F%2Fapi-pilot.ebsi.eu%2Fauthorisation%2Fv2%2Fsiop-sessions&scope=openid+did_authn&nonce=09e8ebfe-674e-4e4c-82b3-da153f8625c2&request=eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJraWQiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3RydXN0ZWQtYXBwcy1yZWdpc3RyeS92My9hcHBzL2F1dGhvcmlzYXRpb24tYXBpX3BpbG90LXRlbXAtMDEifQ.eyJzY29wZSI6Im9wZW5pZCBkaWRfYXV0aG4iLCJyZXNwb25zZV90eXBlIjoiaWRfdG9rZW4iLCJyZXNwb25zZV9tb2RlIjoicG9zdCIsImNsaWVudF9pZCI6Imh0dHBzOi8vYXBpLXBpbG90LmVic2kuZXUvYXV0aG9yaXNhdGlvbi92Mi9zaW9wLXNlc3Npb25zIiwicmVkaXJlY3RfdXJpIjoiaHR0cHM6Ly9hcGktcGlsb3QuZWJzaS5ldS9hdXRob3Jpc2F0aW9uL3YyL3Npb3Atc2Vzc2lvbnMiLCJub25jZSI6IjA5ZThlYmZlLTY3NGUtNGU0Yy04MmIzLWRhMTUzZjg2MjVjMiIsImNsYWltcyI6eyJpZF90b2tlbiI6eyJ2ZXJpZmllZF9jbGFpbXMiOnsidmVyaWZpY2F0aW9uIjp7InRydXN0X2ZyYW1ld29yayI6IkVCU0kiLCJldmlkZW5jZSI6eyJ0eXBlIjp7InZhbHVlIjoidmVyaWZpYWJsZV9jcmVkZW50aWFsIn0sImRvY3VtZW50Ijp7InR5cGUiOnsiZXNzZW50aWFsIjp0cnVlLCJ2YWx1ZSI6WyJWZXJpZmlhYmxlQ3JlZGVudGlhbCIsIlZlcmlmaWFibGVBdXRob3Jpc2F0aW9uIl19LCJjcmVkZW50aWFsU2NoZW1hIjp7ImlkIjp7ImVzc2VudGlhbCI6dHJ1ZSwidmFsdWUiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3RydXN0ZWQtc2NoZW1hcy1yZWdpc3RyeS92Mi9zY2hlbWFzL3pITXA1MkxxSldvY21oQTlSa3puVFd1RWVjSlhvUERLdzNrV1FwODFZWTlwQyJ9fX19fX19fSwiaWF0IjoxNjcyODQxODgxLCJpc3MiOiJhdXRob3Jpc2F0aW9uLWFwaV9waWxvdC10ZW1wLTAxIiwiZXhwIjoxNjcyODQyMTgxfQ.Z8jVzKtcTtSD1kBlYin_1jnfZ6BhhYdo18lUSf5xz0RFtkoPonsQyKsS7u72w7fV3oxWUs8YV7QAynGyUxuR_w"
      description: DID SIOP OIDC URI
    SiopSessionsRequest:
      title: SIOP Session Request
      description: Access token request.
      type: object
      properties:
        id_token:
          type: string
          description: JWS compact serialised ID Token
        vp_token:
          type: string
          description: A Verifiable Presentation JWT. Only for onboarding.
      required:
        - id_token
    Ake1SiopResponse:
      title: SIOP Session Response
      description: Ake1 Response for OAuth2 authentication
      type: object
      properties:
        ake1_enc_payload:
          description: Encrypted payload with user's public key
          type: string
          example: ce527bf1e06bd6241625d54e76bdb5ac029c455f97324ed20a5038724966ba5d9befd49195b4841b513c7f23e785c99f87bad2e255cbceb1152cef05b15137a1411520d8d578961f16d6c59ec042889e45cb4d3965d9d859dac8f217b3b3776ad342a605f2bb985d820ad8b0f6cb2c7c40da4d1ebd3efb5a3d57507e0479801c088e68b277fac799f852c1053a1dacc7cdb921cff2006eaf1b3fa3a5b64de91e991390b7317814625f490a1354dc2b69498b2bfad7caf0e819ebd93cccb2ef26e399d996ab19910605d798dacf9f78489dd7bac8613b5da28314e1153d929a9059decedce00eeb2848ee95f14e523f9f12372e71b9db4ebe702ce508d2dbc1e5cbdafcd5a15afe397fb35f9a45424c6aac43380b054185cbac4f498a5db4dcf517cf8bc760354c26e2e1af37dbdf06f888e5d424a66ab9546475b187787b557d197af20c7ac1e0639acf0304f051194da4be7c8badb0747b3e669ffd7ffe5a2c9c2060f338d8e4eb3010e10e6a67a1c8fe21d48ee7bc5d540497071f80dd36e58d309e868837c193dd5646b33baa61c3c190d5ce44d08bc6820d240e14edd12af9ae8242e5a7186c1697426d14e97101313331cb1d803030cd2d6d2799852bda0dbc80b3c927efffc19d170327ac11c5d645b83c38fdcfb9ac779d9eac795d8eb671fe0ade56cdcb020261e1bf6d2e1d2fdfc1f954959c2d5516adf3f2abcee298c92b5451e3dee89d1903b8390fe9a426278ec879a59e682eabf8b8f3ad4482de9c636a41e506c82d7d0be1a92d926ba7fb05779f2612a86f8b47e10477b1d6080044d1f983cf3cb81e35af5b3ea4205e1d25ce0b6d20755442904d670380082203e25d4326df0ab47ee8bb404f98d5184a3949e043a0656e856f78f442fb33a2ec63c7347520c796fb721bfc0c6106c0db9e0580ba17aa3f96abf1a4744256635803f90bcfce185ddba20a8635a1c59f68760220ddaf296ac3a582ea953f928290c50f186ea8909a9a94a82b6b1c8204f243a4ed4cef5fd672959cec8359a57ac08c4b41ccb515b963f675af7cf4a9bef97f13942a63678680fb8f9e2de766f3c578d6f5913d7e71aafbd5ebc965b90ce4c3dc4a7bc2af74754c3e7c05fc3fbd1851ee5caa4723fe7bf5a9cd804a979bbd341836bcb3e82ad164748cb46f5d9fd4b599d27a307962eea6465eb91a6155
        ake1_jws_detached:
          description: Detached JWS of AKE1 Signing Payload
          type: string
          example: eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QiLCJraWQiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3RydXN0ZWQtYXBwcy1yZWdpc3RyeS92My9hcHBzL2F1dGhvcmlzYXRpb24tYXBpX3BpbG90LXRlbXAtMDEifQ..bJ5gwcsgYcRTpMAJYpkUPGSYA962eioQ94Yju7buVGneuCCmelxWH-ZhKxMf7RolebgdVrrnNIIhdTZLJ8NpMw
        ake1_sig_payload:
          type: object
          properties:
            ake1_enc_payload:
              description: Encrypted payload with user's public key
              type: string
              example: ce527bf1e06bd6241625d54e76bdb5ac029c455f97324ed20a5038724966ba5d9befd49195b4841b513c7f23e785c99f87bad2e255cbceb1152cef05b15137a1411520d8d578961f16d6c59ec042889e45cb4d3965d9d859dac8f217b3b3776ad342a605f2bb985d820ad8b0f6cb2c7c40da4d1ebd3efb5a3d57507e0479801c088e68b277fac799f852c1053a1dacc7cdb921cff2006eaf1b3fa3a5b64de91e991390b7317814625f490a1354dc2b69498b2bfad7caf0e819ebd93cccb2ef26e399d996ab19910605d798dacf9f78489dd7bac8613b5da28314e1153d929a9059decedce00eeb2848ee95f14e523f9f12372e71b9db4ebe702ce508d2dbc1e5cbdafcd5a15afe397fb35f9a45424c6aac43380b054185cbac4f498a5db4dcf517cf8bc760354c26e2e1af37dbdf06f888e5d424a66ab9546475b187787b557d197af20c7ac1e0639acf0304f051194da4be7c8badb0747b3e669ffd7ffe5a2c9c2060f338d8e4eb3010e10e6a67a1c8fe21d48ee7bc5d540497071f80dd36e58d309e868837c193dd5646b33baa61c3c190d5ce44d08bc6820d240e14edd12af9ae8242e5a7186c1697426d14e97101313331cb1d803030cd2d6d2799852bda0dbc80b3c927efffc19d170327ac11c5d645b83c38fdcfb9ac779d9eac795d8eb671fe0ade56cdcb020261e1bf6d2e1d2fdfc1f954959c2d5516adf3f2abcee298c92b5451e3dee89d1903b8390fe9a426278ec879a59e682eabf8b8f3ad4482de9c636a41e506c82d7d0be1a92d926ba7fb05779f2612a86f8b47e10477b1d6080044d1f983cf3cb81e35af5b3ea4205e1d25ce0b6d20755442904d670380082203e25d4326df0ab47ee8bb404f98d5184a3949e043a0656e856f78f442fb33a2ec63c7347520c796fb721bfc0c6106c0db9e0580ba17aa3f96abf1a4744256635803f90bcfce185ddba20a8635a1c59f68760220ddaf296ac3a582ea953f928290c50f186ea8909a9a94a82b6b1c8204f243a4ed4cef5fd672959cec8359a57ac08c4b41ccb515b963f675af7cf4a9bef97f13942a63678680fb8f9e2de766f3c578d6f5913d7e71aafbd5ebc965b90ce4c3dc4a7bc2af74754c3e7c05fc3fbd1851ee5caa4723fe7bf5a9cd804a979bbd341836bcb3e82ad164748cb46f5d9fd4b599d27a307962eea6465eb91a6155
            ake1_nonce:
              description: Nonce used during the authentication process
              type: string
              example: 53a6e914-ef94-412b-b226-82da24be3dd9
            did:
              description: API DID
              type: string
              example: did:ebsi:zbM8cCuoBMFNLeQyLiVFyxw
            iat:
              description: Issued at
              type: number
              example: 1627652364
            exp:
              description: Expires
              type: number
              example: 1627653264
            iss:
              description: Issuer (Authorisation API)
              type: string
              example: authorisation-api_pilot-temp-01
        kid:
          description: API KID
          type: string
          example: https://api-pilot.ebsi.eu/trusted-apps-registry/v3/apps/authorisation-api_pilot-temp-01
    OAuth2SessionsRequest:
      title: OAuth2 Session Request
      description: Request for JWT bearer assertion grant.
      type: object
      properties:
        grantType:
          description: |
            Grant type. Must be set to "client_credentials"
          type: string
          example: client_credentials
        clientAssertionType:
          description: |
            Client Assertion type. Must be set to "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
          type: string
          example: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
        clientAssertion:
          type: string
          description: Self-signed JWT
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksiLCJraWQiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3RydXN0ZWQtYXBwcy1yZWdpc3RyeS92My9hcHBzL3Rlc3QtYXBwLXBpbG90MiJ9.eyJpYXQiOjE2NzI4NDUxOTYsImV4cCI6MTY3Mjg0NTIxMSwianRpIjoiZDQwNzdmMzctNzMxYy00Y2M0LThmYmItZDE0MWE5MjUyODViIiwiYXVkIjoibGVkZ2VyLWFwaSIsInN1YiI6InRlc3QtYXBwLXBpbG90MiIsIm5vbmNlIjoiOWEzNTQxODQtMzlmMy00MGJiLTg1NDctMjc5N2YzZDhlNThhIiwiaXNzIjoidGVzdC1hcHAtcGlsb3QyIn0.enmQemuwwkBSPTokpUjacOSgjM4JIo6OnHLaOiw_A3lwwJqGssBjHOfrxEIVOBCvdtLOSFDa6he8qCnqGef95Q
        scope:
          type: string
          description: Scope is used to define the authentication method. Must be set to "openid did_authn"
          example: openid did_authn
      required:
        - grantType
        - clientAssertionType
        - clientAssertion
        - scope
    Ake1OAuth2Response:
      title: OAuth2 Session Response
      type: object
      properties:
        ake1_enc_payload:
          description: Encrypted payload with user's public key
          type: string
          example: a5c94fe3c30baec627ab0afb26cf4b5f0319f3eb08752991fb98149e16549a2be069461ce0de3b83f3066027da8565d4516d043c1572b837a0263ffe493c5ded124bf4aaf060e87006e21d4b658abf43b6953f1f23ff982acc74d2c341545f976c5052e07730b304aa6bd37bbc8f54535c6ff84fffcf6caadb1757a854c8d559000bd1fb255e83b2e6a79e5a23a7b67c429ffa4a3e1a7acdc18c4cc7b623584a2ce612ae8052ecc42e116a0664c85c0c30f366c9a42d8d3ffc76e0da3b2c16e0cf19a90086d9c0f9db05218197f8bf07060d27b5c6caac3afdb90b4292123f80df6dbd7922b975335f408b74671790413e02c30d9db9ca96cb9bc25a9e51853f408bd565cadfaaf06526799deb2be248d67c82aaf13010dddaa40dbffe2e0e1fb5689ccbca3785707e188d2cf10f320aca678ff48491d4dec3227e2c17c9843fd8283ce79a3ee212c81063248507dbb694c11eb893235e0b6dc69e78eb69c4fc85ecaa91c8c72c43fd5362fe1f382f57f4dd7b0ee03a5542c83602a437e4b03fb434f6a44e4a04f0adbf30abacdaa69a5b826c77ac3faa27a650f3bcff21cdd1f6793df3dad9bae33496c9da4acba4c8fd793bc23f0d9032d416e753cd802153dc0ea3925d1110367322cba5450ceceb3cd3d4228228177dd8d667eda5691030183e0d3f1be40ac793d1d42af344895d85fb84d9374a344e8f95a33b1c740fa4c84ee016765a63fceda74d5decbf5ee76df9119c73491449a70554541900348b306ab07111312d2b74c226df7f194be00b8335a207bd41399487bd4216edf078a11b8a8b9b93d50e2cb673ccbce0b97d994b54b97068ef317e1136193b17d34764e6ec9c68be69b42aaf1aa1c9bb448dd38eb3a96957fc0a5b81c4710921c6605da420614042518739a02f8ed44338236733a5b2964a3bba2e4333034cb14746e6c2692445c65e8ec124c8e49413d01d86cd1b3dbd863807dc1d9a408e47c46c02f3e7bacbcbc387b03ebd26be6bd1d6f70f5c308081a8ca66beaea71ffee9d1cc375fc299323c938f5c200a2f031380f5347d1604d57a4af3c35a4891e5b1e2bb8573e36a4e1af5fbe62e1b188d119a6b07b25bda8086f3f0aa2139ee4e7144cd
        ake1_jws_detached:
          description: Detached JWS of AKE1 Signing Payload
          type: string
          example: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksiLCJraWQiOiJodHRwczovL2FwaS1waWxvdC5lYnNpLmV1L3RydXN0ZWQtYXBwcy1yZWdpc3RyeS92My9hcHBzL2F1dGhvcmlzYXRpb24tYXBpX3BpbG90LXRlbXAtMDEifQ..PHbuIxA7oSp8-6oh7BED0fEiFL8gItKETlFzaiuFIKH0aF3RRjJQv-CKc5kEfmhGSO8_46yD2qFXZnsTrHAJFg
        ake1_sig_payload:
          type: object
          properties:
            ake1_enc_payload:
              description: Encrypted payload with user's public key
              type: string
              example: a5c94fe3c30baec627ab0afb26cf4b5f0319f3eb08752991fb98149e16549a2be069461ce0de3b83f3066027da8565d4516d043c1572b837a0263ffe493c5ded124bf4aaf060e87006e21d4b658abf43b6953f1f23ff982acc74d2c341545f976c5052e07730b304aa6bd37bbc8f54535c6ff84fffcf6caadb1757a854c8d559000bd1fb255e83b2e6a79e5a23a7b67c429ffa4a3e1a7acdc18c4cc7b623584a2ce612ae8052ecc42e116a0664c85c0c30f366c9a42d8d3ffc76e0da3b2c16e0cf19a90086d9c0f9db05218197f8bf07060d27b5c6caac3afdb90b4292123f80df6dbd7922b975335f408b74671790413e02c30d9db9ca96cb9bc25a9e51853f408bd565cadfaaf06526799deb2be248d67c82aaf13010dddaa40dbffe2e0e1fb5689ccbca3785707e188d2cf10f320aca678ff48491d4dec3227e2c17c9843fd8283ce79a3ee212c81063248507dbb694c11eb893235e0b6dc69e78eb69c4fc85ecaa91c8c72c43fd5362fe1f382f57f4dd7b0ee03a5542c83602a437e4b03fb434f6a44e4a04f0adbf30abacdaa69a5b826c77ac3faa27a650f3bcff21cdd1f6793df3dad9bae33496c9da4acba4c8fd793bc23f0d9032d416e753cd802153dc0ea3925d1110367322cba5450ceceb3cd3d4228228177dd8d667eda5691030183e0d3f1be40ac793d1d42af344895d85fb84d9374a344e8f95a33b1c740fa4c84ee016765a63fceda74d5decbf5ee76df9119c73491449a70554541900348b306ab07111312d2b74c226df7f194be00b8335a207bd41399487bd4216edf078a11b8a8b9b93d50e2cb673ccbce0b97d994b54b97068ef317e1136193b17d34764e6ec9c68be69b42aaf1aa1c9bb448dd38eb3a96957fc0a5b81c4710921c6605da420614042518739a02f8ed44338236733a5b2964a3bba2e4333034cb14746e6c2692445c65e8ec124c8e49413d01d86cd1b3dbd863807dc1d9a408e47c46c02f3e7bacbcbc387b03ebd26be6bd1d6f70f5c308081a8ca66beaea71ffee9d1cc375fc299323c938f5c200a2f031380f5347d1604d57a4af3c35a4891e5b1e2bb8573e36a4e1af5fbe62e1b188d119a6b07b25bda8086f3f0aa2139ee4e7144cd
            ake1_nonce:
              description: Nonce used during the authentication process
              type: string
              example: 9a354184-39f3-40bb-8547-2797f3d8e58a
            kid:
              description: Trusted App KID
              type: string
              example: https://api-pilot.ebsi.eu/trusted-apps-registry/v3/apps/test-app-pilot2
            iat:
              description: Issued at
              type: number
              example: 1672845197
            exp:
              description: Expires
              type: number
              example: 1672846097
            iss:
              description: Issuer (Authorisation API)
              type: string
              example: authorisation-api_pilot-temp-01
        kid:
          description: API KID
          type: string
          example: https://api-pilot.ebsi.eu/trusted-apps-registry/v3/apps/authorisation-api_pilot-temp-01
      description: Ake1 Response for OAuth2 authentication
  responses:
    "400":
      description: Bad Request
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
          examples:
            Bad Request:
              $ref: "#/components/examples/BadRequest"
            Token Expired:
              $ref: "#/components/examples/TokenExpired"
            Issuer Not Found:
              $ref: "#/components/examples/IssuerNotFound"
    "500":
      description: Internal Error
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/ProblemDetails"
          examples:
            Internal Server Error:
              $ref: "#/components/examples/InternalError"
  examples:
    BadRequest:
      value:
        title: Bad Request
        status: 400
        detail: Bad request.
    IssuerNotFound:
      value:
        title: Issuer Not Found
        status: 400
        detail: Issuer not found in the trusted apps registry.
    TokenExpired:
      value:
        title: Token Expired
        status: 400
        detail: The token has expired.
    InternalError:
      value:
        title: Internal Server Error
        status: 500
        detail: The server encountered an internal error and was unable to process your request.
