openapi: 3.0.3
info:
  title: Proxy Data Hub API
  version: 2.0.0
  description: |
    Proxy Data API is a Core Service of the EBSI platform providing the
    capability of securely storing data controlled by the owner.

    For more information see:
    * [Technical Specifications](https://ec.europa.eu/digital-building-blocks/wikis/display/EBSIDOC/Proxy+Data+Hub+API)
    * [Code Repository](https://ec.europa.eu/digital-building-blocks/code/projects/EBSI/repos/proxy-data-hub-api/browse)
  termsOfService: "/docs/terms"
  contact:
    name: EBSI Support - Service Desk
    url: https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/11
  license:
    name: "EUPL-1.2"
    url: "https://joinup.ec.europa.eu/page/eupl-text-11-12"
servers:
  - url: "https://api.ebsi.xyz"
    description: EBSI Testing Environment
paths:
  "/proxy-data-hub/v2/attributes":
    get:
      summary: List attributes
      description: Retrieves attributes from the Proxy Data Hub.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/Attribute"
                  links:
                    $ref: "#/components/schemas/Links"
                  pageSize:
                    type: integer
                    description: Number of items to be returned per page.
                  total:
                    type: integer
                    description: Total number of pages in a collection.
              examples:
                Get Attributes:
                  value:
                    items:
                      - storageUri: "https://api.test.intebsi.xyz/storage/v2/stores/distributed"
                        hash: "0x7ee0d94aab0e4f36eae85127056de08433591304a83ff8801bb9212b624f1321"
                        did: "did:ebsi:zub5ZZUfHLLptCduwEy8xRj"
                        visibility: private
                        sharedWith: ""
                        contentType: application/ld+json
                        data: "<bytes for base64url>"
                        dataLabel: document
                      - storageUri: "https://api.test.intebsi.xyz/storage/v2/stores/distributed"
                        hash: "0x7ee0d94aab0e4f36eae85127056de08433591304a83ff8801bb9212b624f1321"
                        did: "did:ebsi:zub5ZZUfHLLptCduwEy8xRj"
                        visibility: private
                        sharedWith: ""
                        contentType: application/ld+json
                        data: "<bytes for base64url>"
                        dataLabel: document
                    total: 13
                    pageSize: 2
                    links:
                      first: "/proxy-data-hub/v2/attributes?page[after]=0&page[size]=2"
                      prev: "/proxy-data-hub/v2/attributes?page[after]=2&page[size]=2"
                      next: "/proxy-data-hub/v2/attributes?page[after]=4&page[size]=2"
                      last: "/proxy-data-hub/v2/attributes?page[after]=13&page[size]=2"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: "The format of the parameter is not valid"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
      security:
        - bearerAuth: []
      operationId: get-proxy-data-hub-v2-attributes-did
      parameters:
        - in: query
          name: "page[after]"
          schema:
            type: string
          description: |
            Cursor that points to the end of the page of data that has been
            returned.
        - schema:
            type: integer
          in: query
          name: "page[size]"
          description: Defines the maximum number of objects that may be returned.
    post:
      summary: Create an attribute
      description: Stores an attribute to the Proxy Data Hub.
      requestBody:
        description: Attribute with its metadata to be stored with a given visibility (shared or private).
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AttributeRequest"
            examples:
              New Attribute:
                value:
                  storageUri: "https://api.test.intebsi.xyz/storage/v2/stores/distributed"
                  visibility: private
                  sharedWith: ""
                  did: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ
                  contentType: application/ld+json
                  dataLabel: document
                  data: "<bytes for base64url>"
                  proof: {}
        required: true
      responses:
        "201":
          description: Create a new attribute
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Attribute"
              examples:
                Created:
                  value:
                    storageUri: "https://api.test.intebsi.xyz/storage/v2/stores/distributed"
                    hash: "0x7ee0d94aab0e4f36eae85127056de08433591304a83ff8801bb9212b624f1321"
                    did: "did:ebsi:zub5ZZUfHLLptCduwEy8xRj"
                    visibility: private
                    sharedWith: ""
                    contentType: application/ld+json
                    dataLabel: document
                    data: "<bytes for base64url>"
        "400":
          description: Unformatted error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {hash} Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: "The {hash} parameter is not valid"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "500":
          description: Internal Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
      security:
        - bearerAuth: []
      operationId: post-proxy-data-hub-v2-attributes-hash
  "/proxy-data-hub/v2/attributes/{hash}":
    parameters:
      - name: hash
        in: path
        schema:
          type: string
          example: "7ee0d94aab0e4f36eae85127056de08433591304a83ff8801bb9212b624f1321"
        required: true
        description: Hash of the attribute.
    get:
      summary: Get an attribute
      description: Gets an attribute identified by its hash.
      operationId: get-proxy-data-hub-v2-private-attributes-hash
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Attribute"
              examples:
                Success:
                  value:
                    storageUri: "https://api.test.intebsi.xyz/storage/v2/stores/distributed"
                    hash: "0x7ee0d94aab0e4f36eae85127056de08433591304a83ff8801bb9212b624f1321"
                    did: "did:ebsi:zub5ZZUfHLLptCduwEy8xRj"
                    visibility: private
                    sharedWith: ""
                    contentType: application/ld+json
                    dataLabel: document
                    data: "<bytes for base64url>"
        "400":
          description: Unformatted error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {hash} parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: "The {hash} parameter is not valid"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Hash does not exist
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "Hash parameter not found"
        "500":
          description: Internal Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
      security:
        - bearerAuth: []
    patch:
      summary: Patch an attribute
      description: Patches an attribute identified by its hash.
      operationId: patch-proxy-data-hub-v2-private-attributes-hash
      requestBody:
        required: true
        content:
          application/json-patch+json:
            schema:
              $ref: "#/components/schemas/Patch"
            examples:
              Patch metadata:
                value:
                  - op: replace
                    path: /contentType
                    value: application/ld+json
        description: JSON Patch standard
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Attribute"
              examples:
                Success:
                  value:
                    storageUri: "https://api.test.intebsi.xyz/storage/v2/stores/distributed"
                    hash: "0x7ee0d94aab0e4f36eae85127056de08433591304a83ff8801bb9212b624f1321"
                    did: "did:ebsi:zub5ZZUfHLLptCduwEy8xRj"
                    visibility: private
                    sharedWith: ""
                    contentType: application/ld+json
                    dataLabel: document
                    data: "<bytes for base64url>"
        "400":
          description: Unformatted error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {hash} parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: "The {hash} parameter is not valid"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Hash does not exist
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "Hash parameter not found"
        "500":
          description: Internal Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
      security:
        - bearerAuth: []
    delete:
      summary: Delete an attribute
      description: Deletes an attribute identified by its hash.
      operationId: delete-proxy-data-hub-v2-attributes-hash
      responses:
        "204":
          description: Attribute deleted
        "400":
          description: Unformatted error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {hash} parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: "The {hash} parameter is not valid"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Hash does not exist
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "Hash parameter not found"
        "500":
          description: Internal Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
      security:
        - bearerAuth: []
components:
  schemas:
    Attribute:
      type: object
      description: Attribute
      example:
        Attribute example:
          storageUri: "https://api.test.intebsi.xyz/storage/v2/stores/distributed"
          hash: "0x7ee0d94aab0e4f36eae85127056de08433591304a83ff8801bb9212b624f1321"
          did: "did:ebsi:zub5ZZUfHLLptCduwEy8xRj"
          visibility: private
          sharedWith: ""
          contentType: application/ld+json
          dataLabel: document
          data: "<bytes for base64url>"
      title: Attribute
      properties:
        storageUri:
          type: string
          description: URI of the Proxy Data Hub Storage to access
          example: "https://api.test.intebsi.xyz/storage/v2/stores/distributed"
        did:
          type: string
          description: User Decentralized Identifier
          example: "did:ebsi:zub5ZZUfHLLptCduwEy8xRj"
        hash:
          type: string
          description: Hash of the attribute.
          example: "0x7ee0d94aab0e4f36eae85127056de08433591304a83ff8801bb9212b624f1321"
        visibility:
          type: string
          enum: [private, shared]
          description: Access of the data to be stored. Options are private (only visible for the owner) or shared (visible for everyone)
        sharedWith:
          type: string
          description: DID with read permissions (applicable when visibility = shared)
        contentType:
          type: string
          description: Content type representing the format of the data registered on the Hub
        dataLabel:
          type: string
          description: Label to be added to the stored data to describe some extra information about the data being stored
        data:
          type: string
          description: base64url encoding of the data to be stored
    AttributeRequest:
      type: object
      title: Attribute Request
      description: Identity Attribute request for creation
      example:
        storageUri: "https://api.test.intebsi.xyz/storage/v2/stores/distributed"
        did: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
        visibility: private
        sharedWith: ""
        contentType: application/ld+json
        dataLabel: document
        data: "<bytes for base64url>"
        proof: {}
      properties:
        storageUri:
          type: string
          description: URI of the Proxy Data Hub Storage to access
          example: "https://api.test.intebsi.xyz/storage/v2/stores/distributed"
        did:
          type: string
          description: User Decentralized Identifier
          example: "did:ebsi:zub5ZZUfHLLptCduwEy8xRj"
        visibility:
          type: string
          enum: [private, shared]
          description: Access of the data to be stored. Options are private (only visible for the owner) or shared (visible for everyone)
        sharedWith:
          type: string
          description: DID wit read permissions (applicable when visibility = shared)
        contentType:
          type: string
          description: Content type representing the format of the data registered on the Hub
        dataLabel:
          type: string
          description: Label to be added to the stored data to describe some extra information about the data being stored
        data:
          type: string
          description: base64url encoding of the data to be stored
        proof:
          type: object
          description: JSON-LD Proof of the request to add an attribute or update its label.
      required:
        - storageUri
        - did
        - contentType
        - data
    Patch:
      title: Patch
      type: array
      description: Format for expressing a sequence of operations to apply to a target JSON document
      items:
        type: object
        properties:
          op:
            type: string
            enum:
              - add
              - remove
              - replace
              - move
              - copy
              - test
            description: Operation to perform
          path:
            type: string
            description: |
              String containing a JSON-Pointer value that references a location within the target
              document where the operation is performed.
          value:
            oneOf:
              - type: string
              - type: object
            description: Value to be added, replaced or tested
          from:
            type: string
            description: Should be used with move, copy and remove operations
        required:
          - op
          - path
      x-examples:
        Replace:
          op: replace
          path: /a/b/c
          value: 42
        Add:
          op: add
          path: /a/b/c
          value:
            - foo
            - bar
        Move:
          op: move
          from: /a/b/c
          path: /a/b/d
        Copy:
          op: copy
          from: /a/b/c
          path: /a/b/e
        Remove:
          op: remove
          path: /a/b/c
        Test:
          op: test
          path: /a/b/c
          value: foo
    ProblemDetails:
      title: Problem Details
      description: A [Problem Details](https://datatracker.ietf.org/doc/html/rfc7807) object.
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type.
          default: "about:blank"
        title:
          type: string
          description: |
            A short summary of the problem type.
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem.
          example: Connection timeout
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
    Links:
      title: Links
      description: Pagination links.
      type: object
      properties:
        last:
          type: string
          description: URI of the last page
        prev:
          type: string
          description: URI of the previous page
        next:
          type: string
          description: URI of the next page
        first:
          type: string
          description: URI of the first page
      x-examples:
        links example:
          first: "/proxy-data-hub/v2/attributes?page[after]=0&page[size]=2"
          prev: "/proxy-data-hub/v2/attributes?page[after]=2&page[size]=2"
          next: "/proxy-data-hub/v2/attributes?page[after]=4&page[size]=2"
          last: "/proxy-data-hub/v2/attributes?page[after]=13&page[size]=2"
  examples:
    Forbidden:
      value:
        title: Forbidden
        status: 403
        detail: Forbidden.
    Unauthorized:
      value:
        title: Unauthorized
        status: 401
        detail: You are not authorized to access the resources.
    InternalError:
      value:
        title: Internal Server Error
        status: 500
        detail: |
          The server encountered an internal error and was unable to complete
          your request.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
