openapi: 3.0.3
info:
  title: Ledger API
  description: |
    Ledger API is a Core Service of the EBSI platform providing access to the EBSI Ledger Protocols and Smart Contracts services of the lower layer Chain & Storage. In v1 we provide capabilities to interact with Hyperledger Besu and Fabric ledgers.

    For Besu, we are exposing a selected set of BESU RPC native APIs. Write operations require authentication.

    For Fabric, we start in v1 by providing an initial set of read REST API to interact with the ledger.
  license:
    name: EUPL-1.2
    url: "https://joinup.ec.europa.eu/page/eupl-text-11-12"
  version: 1.0.0
  contact:
    name: EBSI Support
    url: "https://ec.europa.eu/cefdigital/wiki/display/CEFDIGITAL/ebsi"
  termsOfService: "/docs/terms"
tags:
  - name: Authentication
    description: Authenticate to Ledger API
  - name: Besu
    description: Interaction with Besu blockchain
  - name: Fabric
    description: Hyperledger Fabric REST APIs
    externalDocs:
      url: "http://docs.my-api.com/store-orders.htm"
paths:
  /ledger/v1/sessions:
    post:
      operationId: post-ledger-v1-sessions
      tags:
        - Authentication
      summary: Login to Ledger
      description: Login to Ledger API
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SessionsRequest"
        required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SessionsResponse"
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Bad Request:
                  $ref: "#/components/examples/BadRequest"
                Invalid Token:
                  $ref: "#/components/examples/InvalidToken"
                Issuer Not Found:
                  $ref: "#/components/examples/IssuerNotFound"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /ledger/v1/blockchains/fabric/channels:
    get:
      tags:
        - Fabric
      summary: Get a list of all the available channels
      description: Returns a list of all the available EBSI Fabric channels.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    description: List of channel names.
                    items:
                      $ref: "#/components/schemas/channel"
                  links:
                    $ref: "#/components/schemas/links"
                  total:
                    type: integer
                    description: "Total number of pages in a collection."
                  pageSize:
                    type: integer
                    description: "Number of items to be return per page."
              examples:
                Get Available Channels:
                  value:
                    items:
                      - channelA
                      - channelB
                    total: 13
                    pageSize: 2
                    links:
                      self: "/ledger/v1/blockchains/fabric/channels?page[after]=3&page[size]=2"
                      first: "/ledger/v1/blockchains/fabric/channels?page[after]=0&page[size]=2"
                      prev: "/ledger/v1/blockchains/fabric/channels?page[after]=2&page[size]=2"
                      next: "/ledger/v1/blockchains/fabric/channels?page[after]=4&page[size]=2"
                      last: "/ledger/v1/blockchains/fabric/channels?page[after]=13&page[size]=2"
        "500":
          description: Internal Server Error
          content:
            "application/problem+json":
              schema:
                type: object
                properties:
                  title:
                    type: string
                  status:
                    type: number
                  detail:
                    type: string
              examples:
                Internal Server Error:
                  value:
                    title: Internal Server Error
                    status: 500
                    detail: Server encountered an internal error and was unable to complete your request.
      security:
        - bearerAuth: []
      operationId: get-ledger-bc-fabric-v1-channels
      parameters:
        - in: query
          name: "page[after]"
          schema:
            type: string
          description: Cursor that points to the end of the page of data that has been returned.
        - schema:
            type: integer
          in: query
          name: "page[size]"
          description: Defines the maximum number of objects that may be returned.
    parameters: []
  "/ledger/v1/blockchains/fabric/channels/{channel}":
    get:
      tags:
        - Fabric
      description: Check if channel exists
      summary: Check if channel exists
      responses:
        "204":
          description: Succes. Channel exists.
        "400":
          description: "Bad request. The format of the {channel} parameter is not valid."
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Invalid {channel} Parameter:
                  value:
                    title: Bad request
                    status: 400
                    detail: "The format of {channel} parameter is not valid"
        "404":
          description: Channel {channel} not found
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Channel Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "{channel} not found"
        "500":
          description: Internal Server Error
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  value:
                    title: Internal Server Error
                    status: 500
                    detail: The server encountered an internal error and was unable to complete your request.
      security:
        - bearerAuth: []
      operationId: get-ledger-bc-fabric-v1-channel
    parameters:
      - schema:
          type: string
        name: channel
        in: path
        required: true
        description: Fabric channel name.
  "/ledger/v1/blockchains/fabric/channels/{channel}/blocks":
    get:
      tags:
        - Fabric
      summary: Get blocks
      description: Returns a list of blocks of the channel {channel}. By default API returns the last 10 (or less) blocks.
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    description: List of blocks.
                    items:
                      $ref: "#/components/schemas/block"
                  links:
                    $ref: "#/components/schemas/links"
                  total:
                    type: integer
                    description: " Total number of pages in a collection."
                  pageSize:
                    type: integer
                    description: Number of items to be return per page.
              examples:
                Get Blocks:
                  value:
                    items:
                      - blockNum: 1
                        txCount: 1
                        dataHash: 990ebf9a62d7d995aa126fa675139059ed96ac0b57dae8e2277c0cb744563dfc
                        blockHash: 5c8c30b5ab69fe0c267a3d37aa3cbf2d7358288395cdaa35f520fb162861404f
                        preHash: 0355a07b257bac3b223bd29b3bd3e24f5a53a84885d8bf36e278be0b45b04555
                        txhash:
                          - f76ec19619ed05df3d97baf44ccf332547c6bf8197bf9470be0094ab1ef292a3
                        channelName: ebsichannel
                        createdTime: "2020-03-23T15:26:16.236Z"
                      - blockNum: 2
                        txCount: 1
                        dataHash: 0355a07b257bac3b223bd29b3bd3e24f5a53a84885d8bf36e278be0b45b04555
                        blockHash: def8746428f0d8cc45b9b2993a847130e851a15661935330bc191b6858b63a77
                        preHash: af44ccf332547c6bf8197bf9470be0094ab151a15661935330bc191b6858b63a77
                        txhash:
                          - 42d78c9ead6759a293c2aaa78c453c13fcc3c764cc325f2fd58255c5eba1a686
                        channelName: ebsichannel
                        createdTime: "2020-03-23T15:26:16.236Z"
                    total: 13
                    pageSize: 2
                    links:
                      self: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=3&page[size]=2"
                      first: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=0&page[size]=2"
                      prev: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=2&page[size]=2"
                      next: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=4&page[size]=2"
                      last: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=13&page[size]=2"
        "400":
          description: "Bad request the format of {channel} parameter is not valid"
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Invalid {channel} Parameter:
                  value:
                    title: Bad request
                    status: 400
                    detail: "The format of {channel} parameter is not valid"
        "404":
          description: Not Found
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Channel Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "{channel} parameter not found"
        "500":
          description: Internal Server Error
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  value:
                    title: Internal Server Error
                    status: 500
                    detail: The server encountered an internal error and was unable to complete your request.
      security:
        - bearerAuth: []
      operationId: get-ledger-bc-fabric-v1-channel-blocks
      parameters:
        - in: query
          name: "page[after]"
          schema:
            type: string
          description: Cursor that points to the end of the page of data that has been returned.
        - schema:
            type: integer
          in: query
          name: "page[size]"
          description: Defines the maximum number of objects that may be returned.
    parameters:
      - schema:
          type: string
        name: channel
        in: path
        required: true
        description: Fabric channel name.
  "/ledger/v1/blockchains/fabric/channels/{channel}/blocks/{blockNumber}":
    get:
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/block"
              examples:
                "Get Block 15":
                  value:
                    blockNum: 15
                    txCount: 1
                    dataHash: 990ebf9a62d7d995aa126fa675139059ed96ac0b57dae8e2277c0cb744563dfc
                    blockHash: 5c8c30b5ab69fe0c267a3d37aa3cbf2d7358288395cdaa35f520fb162861404f
                    preHash: 0355a07b257bac3b223bd29b3bd3e24f5a53a84885d8bf36e278be0b45b04555
                    txhash:
                      - f76ec19619ed05df3d97baf44ccf332547c6bf8197bf9470be0094ab1ef292a3
                    channelName: ebsichannel
                    createdTime: "2020-03-23T15:26:16.236Z"
        "400":
          description: "Bad request the format of {channel} or {blockNumber}  parameter is not valid"
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Invalid {channel} Parameter:
                  value:
                    title: Bad request
                    status: 400
                    detail: "The format of {channel} parameter is not valid"
        "404":
          description: Not Found
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Channel Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "{channel} parameter not found"
                Block Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "{blockNumber} parameter not found"
        "500":
          description: Internal Server Error
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  value:
                    title: Internal Server Error
                    status: 500
                    detail: The server encountered an internal error and was unable to complete your request.
      security:
        - bearerAuth: []
      operationId: get-ledger-bc-fabric-v1-channel-block-number
      summary: Get block by number
      tags:
        - Fabric
      description: Returns block for the specified channel and block number
    parameters:
      - schema:
          type: string
        name: channel
        in: path
        required: true
        description: Fabric channel name.
      - schema:
          type: integer
        name: blockNumber
        in: path
        required: true
        description: Block number.
  "/ledger/v1/blockchains/fabric/channels/{channel}/transactions":
    get:
      tags:
        - Fabric
      summary: Get transactions
      description: Returns the last 10 (or less) transactions of the channel
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  pageSize:
                    type: integer
                    description: "Number of items to be return per page."
                  total:
                    type: integer
                    description: "Total number of pages in a collection."
                  links:
                    $ref: "#/components/schemas/links"
                  items:
                    type: array
                    description: list of transactions
                    items:
                      $ref: "#/components/schemas/transaction"
              examples:
                Transaction List:
                  value:
                    items:
                      - txHash: 10f75d8ead6759a293c2aaa78c453c13fcc3c764cc325f2fd58255c5eba1a686
                        validationCode: VALID
                        payloadProposalHash: def8746428f0d8cc45b9b2993a847130e851a15661935330bc191b6858b63a77
                        creatorMspId: EbsiNode1MSP
                        endorserMspId: "EbsiNode1MSP,EbsiNode2MSP,EbsiNode3MSP"
                        chaincodeName: taxudchaincode
                        type: ENDORSER_TRANSACTION
                        createdAt: "2020-03-23T13:30:20.103Z"
                        channelName: ebsichannel
                      - txHash: 42d78c9ead6759a293c2aaa78c453c13fcc3c764cc325f2fd58255c5eba1a686
                        validationCode: INVALID
                        payloadProposalHash: def8746428f0d8cc45b9b2993a847130e851a15661935330bc191b6858b63a77
                        creatorMspId: EbsiNode1MSP
                        endorserMspId: "EbsiNode1MSP,EbsiNode2MSP,EbsiNode3MSP"
                        chaincodeName: taxudchaincode
                        type: ENDORSER_TRANSACTION
                        createdAt: "2020-03-23T13:30:20.103Z"
                        channelName: ebsichannel
                    total: 13
                    pageSize: 2
                    links:
                      self: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=3&page[size]=2"
                      first: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=0&page[size]=2"
                      prev: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=2&page[size]=2"
                      next: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=4&page[size]=2"
                      last: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=13&page[size]=2"
        "400":
          description: "Bad request the format of {channel} parameter is not valid"
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Invalid {channel} Parameter:
                  value:
                    title: Bad request
                    status: 400
                    detail: "The format of {channel} parameter is not valid"
        "404":
          description: Channel not found
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Channel Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "{channel} parameter not found"
        "500":
          description: Internal Server Error
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  value:
                    title: Internal Server Error
                    status: 500
                    detail: The server encountered an internal error and was unable to complete your request.
      security:
        - bearerAuth: []
      operationId: get-ledger-bc-fabric-v1-channel-txs
      parameters:
        - in: query
          name: "page[after]"
          schema:
            type: string
          description: Cursor that points to the end of the page of data that has been returned.
        - schema:
            type: integer
          in: query
          name: "page[size]"
          description: "Number of items to be return per page."
    parameters:
      - schema:
          type: string
        name: channel
        in: path
        required: true
        description: Fabric channel name
  /ledger/v1/blockchains/fabric/channels/{channel}/transactions/{transactionId}:
    get:
      tags:
        - Fabric
      summary: Get transaction details
      description: Return transaction details
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/transaction"
              examples:
                Transaction:
                  value:
                    txHash: ca926ad2367b0f194ab6acccfa331a35c45575eb4874d518e4b355d2a808acc7
                    validationCode: VALID
                    payloadProposalHash: 008df9b7662d2dd1baeeda1dbdf428f72f7b823953a1bc1ff9c6afdc689fb648
                    creatorMspId: EbsiNode1MSP
                    endorserMspId: "EbsiNode1MSP,EbsiNode2MSP,EbsiNode3MSP"
                    chaincodeName: taxudchaincode
                    type: ENDORSER_TRANSACTION
                    createdAt: "2020-03-23T13:30:20.103Z"
                    channelName: ebsichannel
        "400":
          description: "Bad request the format of {channel} or {transactionId} parameter is not valid"
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Invalid {transactionId} Parameter:
                  value:
                    title: Bad request
                    status: 400
                    detail: "The format of {transactionId} parameter is not valid"
        "404":
          description: Not Found
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Channel Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "{channel} parameter not found"
                Transaction Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "{transactionId} parameter not found"
        "500":
          description: Internal Server Error
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Channel Internal Server Error:
                  value:
                    title: Internal Server Error
                    status: 500
                    detail: The server encountered an internal error and was unable to complete your request.
      security:
        - bearerAuth: []
      operationId: get-ledger-bc-fabric-v1-channel-tx-id
    parameters:
      - schema:
          type: string
        name: channel
        in: path
        required: true
        description: Fabric channel name
      - schema:
          type: string
        name: transactionId
        in: path
        required: true
        description: transaction identifier
  /ledger/v1/blockchains/besu:
    post:
      operationId: post-ledger-v1-blockchains-besu
      tags:
        - Besu
      summary: Hyperledger Besu RPC APIs
      description: "Proxy to the Json RPC node of Besu Blockchain. Methods to read the blockchain do not require an auth token."
      requestBody:
        description: |
          The body follows the [JSON-RPC 2.0 specification](https://www.jsonrpc.org/specification). It requires the following fields:

          - **jsonrpc**: Must be exactly '2.0'
          - **method**: Besu RPC native method that needs to be invoked. The list of all possible methods can be found at [eth JSON RPC](https://github.com/ethereum/wiki/wiki/JSON-RPC).
          - **params**: Array of parameters
          - **id**: Identifier stablished by the client
        content:
          application/json:
            schema:
              required:
                - jsonrpc
                - id
                - method
                - params
              type: object
              properties:
                jsonrpc:
                  description: Must be exactly '2.0'
                  type: string
                method:
                  description: Besu RPC native method that needs to be invoked
                  type: string
                params:
                  description: Array of parameters
                  type: array
                  items:
                    type: string
                id:
                  description: Identifier stablished by the client
                  type: integer
                  example: 1
            examples:
              Get Block:
                value:
                  jsonrpc: "2.0"
                  method: eth_getBlockByNumber
                  params:
                    - "123456"
                    - true
                  id: 1
              Get Transaction:
                value:
                  jsonrpc: "2.0"
                  method: eth_getTransactionByHash
                  params:
                    - "0x88df016429689c079f3b2f6ad39fa052532c56795b733da78a91ebe6a713944b"
                  id: 1
              Send Transaction:
                value:
                  jsonrpc: "2.0"
                  method: eth_sendRawTransaction
                  params:
                    - "---signed raw transation---"
                  id: 1
        required: true
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BesuResponse"
              examples:
                Get Block:
                  value:
                    jsonrpc: "2.0"
                    id: 1
                    result:
                      number: "0x1e240"
                      hash: "0x266bd6a41047c0929ebedd56cae148caab0d20a23aa1895bb95524a300ef9187"
                      parentHash: "0x705094eb8ca67929254bedaff973d254311d72a38dc2b95a8711682f034fd3b4"
                      nonce: "0x0000000000000000"
                      sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347"
                      logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
                      transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"
                      stateRoot: "0x4b7559720ae8af08782bcadc07c94243ceaf5fe1d7ee0914d76ad37969791dc4"
                      receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421"
                      miner: "0x7df7b640d9c4c24f563a7d5702499521255fc165"
                      difficulty: "0x1"
                      totalDifficulty: "0x1e241"
                      extraData: "0xf90148a00000000000000000000000000000000000000000000000000000000000000000f854947df7b640d9c4c24f563a7d5702499521255fc165949d2375d1b45b54603a365e23e0197c0a7a8150c894da316adfafdfe6c627e9429176954f25e4a2fb8e94f618d305b3cc3e7181937da874ad07d6f2d67c10808400000000f8c9b841e5e6da6c913c81673972889aeaf5b1dc1b4ae3070ed9dcc3a9e8d7de36a7f778694ff632bdc8fd8964e6b95e592eb17132f8eeb42ebd8044e3646bc7d7154fde01b841e7d6e72d7423f1eb9ba5448fd7c4c2f2770a668bdf187aa3a330e708bf369cf1645ea3d2f03924125509c3aaaef01c1efd8c26122abcd7c96ba080f391d1db6801b841c30e22e5549ed4b06ab8a9f19cd1b41d250e06e5229b945475f2616b9c6eb3a9325a9ea57926da4081a33279a78fab219f803ed638300378e819bb6ffc60479100"
                      size: "0x350"
                      gasLimit: "0x1fffffffffffff"
                      gasUsed: "0x0"
                      timestamp: "0x5e7b16f4"
                      uncles: []
                      transactions: []
                Get Transaction:
                  value:
                    jsonrpc: "2.0"
                    id: 1
                    result:
                      blockHash: "0x1d59ff54b1eb26b013ce3cb5fc9dab3705b415a67127a003c3e61eb445bb8df2"
                      blockNumber: "0x5daf3b"
                      from: "0xa7d9ddbe1f17865597fbd27ec712455208b6b76d"
                      gas: "0xc350"
                      gasPrice: "0x0"
                      hash: "0x88df016429689c079f3b2f6ad39fa052532c56795b733da78a91ebe6a713944b"
                      input: "0x68656c6c6f21"
                      nonce: "0x15"
                      to: "0xf02c1c8e6114b1dbe8937a39260b5b0a374432bb"
                      transactionIndex: "0x41"
                      value: "0xf3dbb76162000"
                      v: "0x25"
                      r: "0x1b5e176d927f8e9ab405058b2d2457392da3e20f328b16ddabcebc33eaac5fea"
                      s: "0x4ba69724e8f69de52f0125ad8b3c5c2cef33019bac3249e2c0a2192766d1721c"
                Send Transaction:
                  value:
                    jsonrpc: "2.0"
                    id: 1
                    result: "0xe670ec64341771606e55d6b4ca35a1a6b75ee3d5145a99d05921026d1527331"
        "400":
          description: Bad request
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Bad Request:
                  $ref: "#/components/examples/BadRequest"
                Invalid Token:
                  $ref: "#/components/examples/InvalidToken"
                Method Disabled:
                  $ref: "#/components/examples/MethodDisabled"
                Invalid Method:
                  $ref: "#/components/examples/MethodNoExists"
        "401":
          description: Unauthorized
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/NoAnonymous"
        "403":
          description: Forbidden
          content:
            "application/problem+json":
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Forbidden:
                  $ref: "#/components/examples/BesuPermissions"
                Deployment Forbidden:
                  $ref: "#/components/examples/NoDeploySC"
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    SessionsRequest:
      description: Request for OAuth 2.0 JWT bearer assertion grant.
      required:
        - grantType
        - assertion
      type: object
      properties:
        grantType:
          description: OAuth 2.0 grant type. Must be set to "urn:ietf:params:oauth:grant-type:jwt-bearer"
          type: string
          example: "urn:ietf:params:oauth:grant-type:jwt-bearer"
        assertion:
          type: string
          description: Self-signed JWT
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
    SessionsResponse:
      description: Authentication JWT
      type: object
      properties:
        accessToken:
          description: Authentication JWT to access the API.
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        tokenType:
          description: Type of the authentication token. Supported type "bearer".
          type: string
          example: Bearer
        expiresIn:
          description: JWT expiration in seconds.
          type: integer
          example: 900
        issuedAt:
          description: "Time of JWT issuance. Format: unix timestamp"
          type: string
          example: "1467841035013"
    BesuResponse:
      type: object
      properties:
        jsonrpc:
          description: Must be exactly '2.0'
          type: string
        id:
          description: Same identifier established by the client in the call
          type: integer
        result:
          description: Result of the call
          type: object
    channel:
      title: channel
      type: string
      x-examples:
        Channel: ebsichannel
      description: hyperledger fabric channel model
    Problem:
      description: A Problem Details object (RFC 7807)
      type: object
      x-examples:
        Not Enough Credit:
          type: "https://example.com/probs/out-of-credit"
          title: You do not have enough credit.
          detail: "Your current balance is 30, but that costs 50."
          instance: /account/12345/msgs/abc
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type.
          default: "about:blank"
        title:
          type: string
          description: |
            A short summary of the problem type.
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          exclusiveMaximum: true
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem.
          example: Connection timeout
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
    block:
      title: block
      type: object
      description: hyperledger fabric block model
      x-examples:
        Block:
          blockNum: 15
          txCount: 1
          dataHash: 990ebf9a62d7d995aa126fa675139059ed96ac0b57dae8e2277c0cb744563dfc
          blockHash: 5c8c30b5ab69fe0c267a3d37aa3cbf2d7358288395cdaa35f520fb162861404f
          preHash: 0355a07b257bac3b223bd29b3bd3e24f5a53a84885d8bf36e278be0b45b04555
          txhash:
            - f76ec19619ed05df3d97baf44ccf332547c6bf8197bf9470be0094ab1ef292a3
          channelName: ebsichannel
          createdTime: "2020-03-23T15:26:16.236Z"
      properties:
        blockNum:
          type: integer
          description: block number
        txCount:
          type: integer
          description: transaction count
        dataHash:
          type: string
          description: data hash
        blockHash:
          type: string
          description: block hash
        preHash:
          type: string
          description: previous block hash
        txHash:
          type: array
          description: transaction hash
          items:
            type: string
        createdTime:
          type: string
          description: time of creation
        channelName:
          type: string
          description: channel name
    transaction:
      title: transaction
      type: object
      description: hyperledger fabric transaction model
      x-examples:
        transaction example:
          txHash: 10f75d8ead6759a293c2aaa78c453c13fcc3c764cc325f2fd58255c5eba1a686
          validationCode: VALID
          payloadProposalHash: def8746428f0d8cc45b9b2993a847130e851a15661935330bc191b6858b63a77
          creatorMspId: EbsiNode1MSP
          endorserMspId: "EbsiNode1MSP,EbsiNode2MSP,EbsiNode3MSP"
          chaincodeName: taxudchaincode
          type: ENDORSER_TRANSACTION
          createdAt: "2020-03-23T13:30:20.103Z"
          channelName: ebsichannel
      properties:
        txHash:
          type: string
          description: transaction hash
        validationCode:
          type: string
          description: validation code
        payloadProposalHash:
          type: string
          description: hash of the proposal message
        creatorMspId:
          type: string
          description: User or node who submitted the transaction
        endorserMspId:
          type: string
          description: MspId of the endorser node
        chaincodeName:
          type: string
          description: chaincode name
        type:
          type: string
          description: transaction type
        createdAt:
          type: string
          description: transaction creation date
        channelName:
          type: string
          description: channel name
    links:
      title: links
      type: object
      properties:
        self:
          type: string
          description: " URI of the current page"
        last:
          type: string
          description: " URI of the last page"
        prev:
          type: string
          description: " URI of the previous page"
        next:
          type: string
          description: " URI of the next page"
        first:
          type: string
          description: " URI of the first page"
      description: links model used for pagination
      x-examples:
        Links:
          self: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=3&page[size]=2"
          first: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=0&page[size]=2"
          prev: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=2&page[size]=2"
          next: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=4&page[size]=2"
          last: "/ledger/v1/blockchains/fabric/channels/ebsichannel/transactions?page[after]=13&page[size]=2"
  examples:
    BesuPermissions:
      value:
        title: Forbidden
        status: 403
        detail: The method 'eth_sendRawTransaction' needs besu permissions
    NoDeploySC:
      value:
        title: Forbidden
        status: 403
        detail: Deployment of new smart contracts is not allowed
    NoAnonymous:
      value:
        title: Unauthorized
        status: 401
        detail: The method 'eth_sendRawTransaction' is not available for anonymous access
    MethodDisabled:
      value:
        title: Bad request
        status: 400
        detail: The method 'eth_compileSolidity' is currently disabled
    MethodNoExists:
      value:
        title: Bad request
        status: 400
        detail: The method 'xxxxxx' does not exist
    BadRequest:
      value:
        title: Bad Request
        status: 400
        detail: Bad request.
    InvalidToken:
      value:
        title: Invalid Token
        status: 400
        detail: Token has expired. Max age of a token is 15 min.
    IssuerNotFound:
      value:
        title: Issuer Not Found
        status: 400
        detail: Issuer not found in the trusted apps registry.
    NotFound:
      value:
        title: Not Found
        status: 404
        detail: Not found.
    InternalError:
      value:
        title: Internal Server Error
        status: 500
        detail: The server encountered an internal error and was unable to complete your request.
servers:
  - url: "http://localhost"
    description: Local Computer Environment
  - url: "https://api.ebsi.xyz"
    description: EBSI Testing Environment
