openapi: 3.1.0
info:
  title: Storage API v3
  version: 3.0.0
  description: |
    The Storage API is a generic supporting Core Service of the EBSI platform
    providing access to the Off-chain Storage services of the lower layer Chain &
    Storage, but will limit in terms of storage capacity, as EBSI Project doesn't
    have the vocation of being a storage cloud provider.

    This API provides read and write storage capabilities of files and Key-Value
    for multiple storage systems:

    * File Storage API: provides CRUD operations for files in the off-chain distributed storage.

    * Key-Value Storage API: provides CRUD operations for Key-Value (with data value in JSON
    format) in the off-chain distributed storage.

    It also has a special JSON-RPC endpoint that serves as a proxy between Core
    APIs and the distributed storage. Only the Storage API has direct access to
    distributed storage infrastructure (Cassandra for v2.0).
  termsOfService: https://api-pilot.ebsi.eu/docs/terms
  contact:
    name: EBSI Support - Service Desk
    url: https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/11
  license:
    name: EUPL-1.2
    url: https://joinup.ec.europa.eu/page/eupl-text-11-12
paths:
  /storage/v3/stores:
    get:
      tags:
        - Stores
      operationId: get-storage-v3-stores
      summary: List stores
      description: Returns a list of available stores.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page[before]
          schema:
            type: string
          description: Cursor that points to the start of the page of data that has been returned.
        - in: query
          name: page[after]
          schema:
            type: string
          description: Cursor that points to the end of the page of data that has been returned.
        - schema:
            type: integer
          in: query
          name: page[size]
          description: Defines the maximum number of objects that may be returned.
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    description: List of available stores
                    items:
                      type: string
                  total:
                    type: integer
                    description: Total number of pages in a collection
                  pageSize:
                    type: integer
                    description: Number of items to be returned per page
                  links:
                    $ref: "#/components/schemas/Links"
              examples:
                Stores:
                  value:
                    items:
                      - distributed
                      - italy
                      - germany
                      - external1
                    total: 4
                    pageSize: 10
                    links:
                      first: /storage/v3/stores?page[after]=1&page[size]=10
                      prev: /storage/v3/stores?page[after]=1&page[size]=10
                      next: /storage/v3/stores?page[after]=1&page[size]=10
                      last: /storage/v3/stores?page[after]=1&page[size]=10
  /storage/v3/stores/{store}:
    get:
      tags:
        - Stores
      operationId: get-storage-v3-stores-distributed
      summary: Check if a store exists
      description: Checks if a store exists.
      security:
        - bearerAuth: []
      parameters:
        - name: store
          in: path
          schema:
            type: string
          example: distributed
          required: true
      responses:
        "204":
          description: Successful
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: The format of parameter is not valid
        "404":
          description: Store does not exist
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: Parameter not found
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /storage/v3/stores/distributed/jsonrpc:
    post:
      operationId: post-storage-v3-stores-distributed-jsonrpc
      tags:
        - Proxy
      summary: Proxy calls to Cassandra
      description: |
        JSON-RPC call that includes the SQL query to interact with cassandra. This endpoint can
        only be used by Notifications API and Proxy Data Hub API.
      security:
        - bearerAuth: []
      requestBody:
        required: true
        description: |
          The body follows the
          [JSON-RPC 2.0 specification](https://www.jsonrpc.org/specification).
          It requires the following fields:

          - **jsonrpc**: Must be exactly '2.0'
          - **method**: Must be exactly 'cassandra_call'
          - **params**: Array of parameters containing the query string and query parameters
          - **id**: Identifier established by the client
        content:
          application/json:
            schema:
              required:
                - jsonrpc
                - id
                - method
                - params
              type: object
              properties:
                jsonrpc:
                  description: Must be exactly '2.0'
                  type: string
                method:
                  description: Must be exactly 'cassandra_call'
                  type: string
                params:
                  description: Array of parameters containing the query string and query parameters
                  type: array
                  items:
                    oneOf:
                      - type: string
                      - type: object
                      - type: number
                id:
                  description: Identifier established by the client
                  type: integer
                  example: 1
            examples:
              Insert Notification:
                value:
                  jsonrpc: "2.0"
                  method: cassandra_call
                  params:
                    - "insert into notification_storage (id, sender, receiver, message) values (?, ?, ?, ?) using ttl ?"
                    - "0x1a04db115c5c5e429c8d45a297a2c4590bf60c97995332ccee1ff1f25a220c02"
                    - did:ebsi:0x14ec91AC9FFa3499bC6a418fc0A5B5531D1a20E3
                    - did:ebsi:0xe08BbfED79c5D66b723086E9D28d70C0d12c9DB8
                    - '{"schemaId":"...", "payload": "...", ...}'
                    - 86400
                  id: 1
              Get Notifications:
                value:
                  jsonrpc: "2.0"
                  method: cassandra_call
                  params:
                    - select * from notification_storage where receiver = ? allow filtering
                    - did:ebsi:0xe08BbfED79c5D66b723086E9D28d70C0d12c9DB8
                  id: 1
              Delete Notification:
                value:
                  jsonrpc: "2.0"
                  method: cassandra_call
                  params:
                    - delete from notification_storage where id = ?
                    - "0x1a04db115c5c5e429c8d45a297a2c4590bf60c97995332ccee1ff1f25a220c02"
                  id: 1
              Insert Attribute:
                value:
                  jsonrpc: "2.0"
                  method: "cassandra_call"
                  params:
                    - "insert into attribute_storage (hash, did, visibility, shared_with, content_type, data, data_label) values (?, ?, ?, ?, ?, ?, ?)"
                    - "0xaed15s2ed21258a2624d2a55de452faed15s2ed21258a2624d2a55de452f5412"
                    - "did:ebsi:0x14ec91AC9FFa3499bC6a418fc0A5B5531D1a20E3"
                    - "private"
                    - ""
                    - "application/ld+json"
                    - "anVsaWFuIGdvbnphbGV6... (encrypted data)"
                    - "document"
                  id: 1
              Get Attributes:
                value:
                  jsonrpc: "2.0"
                  method: cassandra_call
                  params:
                    - select * from attribute_storage where did = ? allow filtering
                    - did:ebsi:0xe08BbfED79c5D66b723086E9D28d70C0d12c9DB8
                  id: 1
              Get Shared Attributes:
                value:
                  jsonrpc: "2.0"
                  method: cassandra_call
                  params:
                    - select * from attribute_storage where shared_with = ? allow filtering
                    - did:ebsi:0xe08BbfED79c5D66b723086E9D28d70C0d12c9DB8
                  id: 1
              Get Attributes with query options:
                value:
                  jsonrpc: "2.0"
                  method: cassandra_call
                  params:
                    - select * from attribute_storage where did = ? allow filtering
                    - did:ebsi:0xe08BbfED79c5D66b723086E9D28d70C0d12c9DB8
                    - fetchSize: 50
                      pageState: "abcdef"
                  id: 1
              Delete Attribute:
                value:
                  jsonrpc: "2.0"
                  method: cassandra_call
                  params:
                    - delete from attribute_storage where hash = ?
                    - "0xaed15s2ed21258a2624d2a55de452faed15s2ed21258a2624d2a55de452f5412"
                  id: 1
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JsonRpcResponse"
              examples:
                Get Notifications:
                  value:
                    jsonrpc: "2.0"
                    id: 1
                    result:
                      rows:
                        - id: "0x1a04db115c5c5e429c8d45a297a2c4590bf60c97995332ccee1ff1f25a220c02"
                          sender: did:ebsi:0x14ec91AC9FFa3499bC6a418fc0A5B5531D1a20E3
                          receiver: did:ebsi:0xe08BbfED79c5D66b723086E9D28d70C0d12c9DB8
                          message: '{"schemaId":"...", "payload": "...", ...}'
                        - id: "8ed504517-e570-4939-8931-973500f25a21"
                          sender: did:ebsi:0x14ec91AC9FFa3499bC6a418fc0A5B5531D1a20E3
                          receiver: did:ebsi:0xe08BbfED79c5D66b723086E9D28d70C0d12c9DB8
                          message: '{"schemaId":"...", "payload": "...", ...}'
        "204":
          description: Success (no content)
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Bad Request:
                  $ref: "#/components/examples/BadRequest"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
  /storage/v3/stores/distributed/files:
    get:
      tags:
        - File Storage
      operationId: get-storage-v3-stores-distributed-files
      summary: List files
      description: Gets a list of files stored in the distributed store.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page[before]
          schema:
            type: string
          description: Cursor that points to the start of the page of data that has been returned.
        - in: query
          name: page[after]
          schema:
            type: string
          description: Cursor that points to the end of the page of data that has been returned.
        - schema:
            type: integer
          in: query
          name: page[size]
          description: Defines the maximum number of objects that may be returned.
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      title: File
                      type: string
                      description: File data model
                  links:
                    $ref: "#/components/schemas/Links"
                  pageSize:
                    type: integer
                    description: Number of items to be returned per page
                  total:
                    type: integer
                    description: Total number of pages in a collection
              examples:
                List of files:
                  value:
                    items:
                      - "0x0355a07b257bac3b223bd29b3bd3e24f5a53a84885d8bf36e278be0b45b04555"
                      - "0x4234a07b257bac3b223bd29b3bd3e24f5a53a84885d8bf36e278be0b45b044df"
                    total: 2
                List of files (pagination):
                  value:
                    items:
                      - "0x0355a07b257bac3b223bd29b3bd3e24f5a53a84885d8bf36e278be0b45b04555"
                      - "0x0355a07b257bac3b223bd29b3bd3e24f5a53a84885d8bf36e278be0b45b04555"
                    total: 13
                    pageSize: 2
                    links:
                      first: /storage/v3/stores/distributed/files?page[after]=1&page[size]=2
                      prev: /storage/v3/stores/distributed/files?page[after]=2&page[size]=2
                      next: /storage/v3/stores/distributed/files?page[after]=4&page[size]=2
                      last: /storage/v3/stores/distributed/files?page[after]=7&page[size]=2
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: The format of {store} parameter is not valid
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "{store} not found"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
    post:
      tags:
        - File Storage
      operationId: post-storage-v3-stores-distributed-files
      summary: Store a file
      description: Stores a file to the distributed storage.
      security:
        - bearerAuth: []
      requestBody:
        description: File to store
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - file
              properties:
                file:
                  type: string
                  description: File to upload
                  format: binary
                metadata:
                  type: string
                  description: File Metadata (stringified JSON)
        required: true
      responses:
        "201":
          description: File stored
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  file store response:
                    hash: "0xbe5b5152fcd01b6bf53f149bfd1493a49ec5e8ae94cc4c29a81563eea0e347f4"
                    function: keccak256
                description: Object returned upon successful file storage
                properties:
                  hash:
                    type: string
                    description: hash of the file stored
                  function:
                    type: string
                    description: 1lgorithm used to generate the file's hash
                required:
                  - hash
                  - function
              examples:
                Success:
                  value:
                    hash: "0xbe5b5152fcd01b6bf53f149bfd1493a49ec5e8ae94cc4c29a81563eea0e347f4"
                    function: keccak256
        "400":
          description: Unformatted error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid Parameter:
                  value:
                    title: Bad request
                    status: 400
                    detail: The format of parameter is not valid
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: Not found
        "413":
          description: Too large
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Too Large:
                  $ref: "#/components/examples/TooLarge"
        "500":
          description: Internal Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /storage/v3/stores/distributed/files/{hash}:
    get:
      tags:
        - File Storage
      operationId: get-storage-v3-stores-distributed-files-hash
      summary: Get a file
      description: Gets a file identified by its hash.
      security:
        - bearerAuth: []
      parameters:
        - name: hash
          in: path
          schema:
            type: string
          example: "0xbe5b5152fcd01b6bf53f149bfd1493a49ec5e8ae94cc4c29a81563eea0e347f4"
          required: true
      responses:
        "200":
          description: Successful response returns a binary file
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {store,hash} Parameter:
                  value:
                    title: Bad request
                    status: 400
                    detail: The format of the {store,hash} parameter is not valid
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "{store,hash} parameter not found"
        "500":
          description: Internal Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
    patch:
      tags:
        - File Storage
      operationId: patch-storage-v3-store-distributed-files-hash
      summary: Patch a file's metadata
      description: Applies a patch to the file's metadata.
      security:
        - bearerAuth: []
      parameters:
        - name: hash
          in: path
          schema:
            type: string
          example: 0xaed15s2ed21258a2624d2a55de452faed15s2ed21258a2624d2a55de452f5412
          required: true
      requestBody:
        required: true
        content:
          application/json-patch+json:
            schema:
              type: array
              description: Format for expressing a sequence of operations to apply to a target JSON document
              items:
                type: object
                properties:
                  op:
                    type: string
                    enum:
                      - add
                      - remove
                      - replace
                      - move
                      - copy
                      - test
                    description: Operation to perform
                  path:
                    type: string
                    description: |
                      String containing a JSON-Pointer value that references a location within the target
                      document where the operation is performed.
                  value:
                    oneOf:
                      - type: string
                      - type: object
                    description: Value to be added, replaced or tested
                  from:
                    type: string
                    description: Should be used with move, copy and remove operations
                required:
                  - op
                  - path
              x-examples:
                Replace:
                  op: replace
                  path: /a/b/c
                  value: 42
                Add:
                  op: add
                  path: /a/b/c
                  value:
                    - foo
                    - bar
                Move:
                  op: move
                  from: /a/b/c
                  path: /a/b/d
                Copy:
                  op: copy
                  from: /a/b/c
                  path: /a/b/e
                Remove:
                  op: remove
                  path: /a/b/c
                Test:
                  op: test
                  path: /a/b/c
                  value: foo
            examples:
              Patch metadata:
                value:
                  - op: replace
                    path: /metadata
                    value:
                      versionId: "2.1"
                      extension: pdf
                      author: Jane Smith
                      date: 123456789
        description: JSON Patch standard
      responses:
        "200":
          description: Object patched
          content:
            application/json:
              schema:
                type: object
                description: Patched object
              examples:
                Success:
                  value:
                    versionId: "2.1"
                    extension: pdf
                    author: Jane Smith
                    date: 123456789
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {store,hash} Parameter:
                  value:
                    title: Bad request
                    status: 400
                    detail: The format of the {store,hash} parameter is not valid
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not Found:
                  value:
                    title: Not found
                    status: 404
                    detail: "{store,key} is not found"
        "413":
          description: Entity Too Large
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Value Too Large:
                  $ref: "#/components/examples/TooLarge"
        "414":
          description: URI Too Long
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Key Too Large:
                  value:
                    title: Key Too Large
                    status: 414
                    detail: The key size exceeds the limit of 256 bytes
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
    delete:
      tags:
        - File Storage
      operationId: delete-storage-v3-stores-distributed-files-hash
      summary: Delete a file
      description: Deletes a file identified by its hash.
      security:
        - bearerAuth: []
      parameters:
        - name: hash
          in: path
          schema:
            type: string
          example: "0xbe5b5152fcd01b6bf53f149bfd1493a49ec5e8ae94cc4c29a81563eea0e347f4"
          required: true
      responses:
        "204":
          description: File deleted
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {store,hash} Parameter:
                  value:
                    title: Bad request
                    status: 400
                    detail: The format of the {store,hash} parameter is not valid
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not Found:
                  value:
                    title: Not found
                    status: 404
                    detail: "{store,hash} parameter not found"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /storage/v3/stores/distributed/files/{hash}/metadata:
    get:
      tags:
        - File Storage
      operationId: get-storage-v3-stores-distributed-files-hash-metadata
      summary: Get a file's metadata
      description: Gets a file's metadata.
      security:
        - bearerAuth: []
      parameters:
        - name: hash
          in: path
          schema:
            type: string
          example: "0xbe5b5152fcd01b6bf53f149bfd1493a49ec5e8ae94cc4c29a81563eea0e347f4"
          required: true
      responses:
        "200":
          description: Returns the metadata
          content:
            application/json:
              schema:
                type: object
              examples:
                Success:
                  value:
                    filename: file1.pdf
                    description: company info
                    hash: 0355a07b257bac3b223bd29b3bd3e24f5a53a84885d8bf36e278be0b45b04555
                    timestamp: "2020-12-31T00:00:00"
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {store,hash} Parameter:
                  value:
                    title: Bad request
                    status: 400
                    detail: The format of the {store,hash} parameter is not valid
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "{store,hash} parameter not found"
        "500":
          description: Internal Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /storage/v3/stores/distributed/key-values:
    get:
      tags:
        - Key-Value Storage
      operationId: get-storage-v3-stores-distributed-key-values
      summary: List key-values
      description: Gets the list of key-values by store.
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: page[before]
          schema:
            type: string
          description: Cursor that points to the start of the page of data that has been returned.
        - in: query
          name: page[after]
          schema:
            type: string
          description: Cursor that points to the end of the page of data that has been returned.
        - schema:
            type: integer
          in: query
          name: page[size]
          description: Defines the maximum number of objects that may be returned.
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: string
                      description: Key from a key-value pair
                  links:
                    type: object
                    properties:
                      next:
                        type: string
                        description: URI of the next page
                    description: Links model used for pagination with Cassandra
                    x-examples:
                      Links:
                        next: /storage/v3/stores?page[after]=4&page[size]=abc123
                  pageSize:
                    type: integer
                    description: Number of items to be returned per page
              examples:
                Success:
                  value:
                    items:
                      - key1
                      - key2
                    pageSize: 2
                    links:
                      next: /storage/v3/stores/distributed/key-values?page[after]=4&page[size]=2
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid Parameter:
                  value:
                    title: Bad request
                    status: 400
                    detail: The format of parameter is not valid
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: Not found
  /storage/v3/stores/distributed/key-values/{key}:
    put:
      tags:
        - Key-Value Storage
      operationId: put-storage-v3-stores-distributed-key-values-key
      summary: Add or update a value
      description: Creates a new entry or updates an existing one.
      security:
        - bearerAuth: []
      parameters:
        - name: key
          in: path
          schema:
            type: string
          example: "key1"
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
            examples:
              Simple Value:
                value: value
        description: "Any string. Size limit: 1MB"
      responses:
        "200":
          description: Object updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  "{key}":
                    type: string
                    example: "{stored value}"
                    description: Key Value example
              examples:
                Success:
                  value:
                    "{key}": "{stored value}"
        "201":
          description: Object created
          content:
            application/json:
              schema:
                type: object
                properties:
                  "{key}":
                    type: string
                    example: '"{stored value}"'
                    description: Key Value example
              examples:
                Success:
                  value:
                    "{key}": "{stored value}"
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Bad Request:
                  value:
                    title: Bad Request
                    status: 400
                    detail: The format of the {store,key} parameter is not valid
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not Found:
                  value:
                    title: Not found
                    status: 404
                    detail: "{store,key} is not found"
        "413":
          description: Entity Too Large
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Value Too Large:
                  $ref: "#/components/examples/TooLarge"
        "414":
          description: URI Too Long
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Key Too Large:
                  value:
                    title: Key Too Large
                    status: 414
                    detail: The key size exceeds the limit of 256 bytes
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
    get:
      tags:
        - Key-Value Storage
      operationId: get-storage-v3-stores-distributed-key-values-key
      summary: Get value
      description: Gets the value associated with the key.
      security:
        - bearerAuth: []
      parameters:
        - name: key
          in: path
          schema:
            type: string
          example: "key1"
          required: true
      responses:
        "200":
          description: Get object
          content:
            application/json:
              schema:
                type: string
              examples:
                Simple Value:
                  value: value
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {store,key} Parameter:
                  value:
                    title: Bad request
                    status: 400
                    detail: The format of the {store,key} parameter is not valid
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not Found:
                  value:
                    title: Not Found
                    status: 404
                    detail: "{store,key} is not found"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
    delete:
      tags:
        - Key-Value Storage
      operationId: delete-storage-v3-stores-distributed-key-values-key
      summary: Delete a key-value
      description: Deletes a key-value
      security:
        - bearerAuth: []
      parameters:
        - name: key
          in: path
          schema:
            type: string
          example: "key1"
          required: true
      responses:
        "204":
          description: Object deleted
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {store,key} Parameter:
                  value:
                    title: Bad request
                    status: 400
                    detail: The format of the {store,key} parameter is not valid
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Not Found:
                  value:
                    title: Not found
                    status: 404
                    detail: "{store,key} is not found"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
components:
  schemas:
    JsonRpcResponse:
      title: JSON-RPC Response
      type: object
      properties:
        jsonrpc:
          description: Must be exactly '2.0'
          type: string
        id:
          description: Same identifier established by the client in the call
          type: integer
        result:
          description: Result of the call
          oneOf:
            - type: object
            - type: string
    Links:
      title: Links
      description: Links model used for pagination.
      type: object
      properties:
        last:
          type: string
          description: URI of the last page
        prev:
          type: string
          description: URI of the previous page
        next:
          type: string
          description: URI of the next page
        first:
          type: string
          description: URI of the first page
      x-examples:
        Links:
          first: /storage/v3/stores?page[after]=1&page[size]=2
          prev: /storage/v3/stores?page[after]=2&page[size]=2
          next: /storage/v3/stores?page[after]=4&page[size]=2
          last: /storage/v3/stores?page[after]=13&page[size]=2
    ProblemDetails:
      title: Problem Details
      description: A [Problem Details](https://datatracker.ietf.org/doc/html/rfc7807) object.
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide
            human-readable documentation for the problem type.
          default: "about:blank"
        title:
          type: string
          description: A short summary of the problem type.
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem.
          example: Connection timeout
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem. It may or may
            not yield further information if dereferenced.
  examples:
    BadRequest:
      value:
        title: Bad Request
        status: 400
        detail: Bad request.
    Unauthorized:
      value:
        title: Unauthorized
        status: 401
        detail: You are not authorized to access the resources.
    Forbidden:
      value:
        title: Forbidden
        status: 403
        detail: Forbidden.
    TooLarge:
      value:
        title: Payload Too Large
        status: 413
        detail: Payload exceedes the size limit {size_limit}.
    InternalError:
      value:
        title: Internal Server Error
        status: 500
        detail: The server encountered an internal error and was unable to complete your request.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
servers:
  - url: http://localhost
    description: Local Computer Environment
  - url: https://api-test.ebsi.eu
    description: EBSI Test Environment
  - url: https://api-pilot.ebsi.eu
    description: EBSI Pilot Environment
  - url: "https://api-conformance.ebsi.eu"
    description: EBSI Conformance Environment
