openapi: 3.0.3
info:
  title: Trusted Ledgers & Smart Contracts Registry API
  version: 2.0.0
  description: |
    Trusted Ledgers & Smart Contracts Registry (TLSCR) API is an EBSI core service. It enables us
    to interact with the Trusted Ledgers & Smart Contracts Registry - Smart Contract to
    - list the trusted smart contract,
    - list the trusted ledgers (on the long term a network of trusted ledger compliant with EBSI
    rules)
    - obtain Smart Contract and Ledger information,
    - optionally it helps to construct unsigned transactions for the operations.

    For more information see:

    * [Technical Specifications](https://ec.europa.eu/digital-building-blocks/wikis/display/EBSIDOC/Trusted+Ledgers+and+Smart+Contracts+Registry+API)
    * [Smart Contract Technical Specifications](https://ec.europa.eu/digital-building-blocks/wikis/pages/viewpage.action?pageId=374834300)
    * [Code Repository](https://ec.europa.eu/digital-building-blocks/code/projects/EBSI/repos/trusted-ledgers-sc-registry-api/browse)
    * [Smart Contract Code](https://ec.europa.eu/digital-building-blocks/code/projects/EBSI/repos/core-services/browse/contracts/trusted-ledgers-registry)
  termsOfService: /docs/terms
  contact:
    name: EBSI Support - Service Desk
    url: https://ec.europa.eu/digital-building-blocks/tracker/plugins/servlet/desk/portal/11
  license:
    name: EUPL-1.2
    url: https://joinup.ec.europa.eu/page/eupl-text-11-12
paths:
  /trusted-ledgers-smart-contracts-registry/v2/ledgers:
    get:
      operationId: get-trusted-ledgers-smart-contracts-registry-v2-ledgers
      summary: List ledgers
      description: Returns a list of ledgers.
      tags:
        - Ledgers
      parameters:
        - in: query
          name: page[after]
          schema:
            type: string
          description: Cursor that points to the end of the page of data that has been returned.
        - schema:
            type: integer
          in: query
          name: page[size]
          description: Defines the maximum number of objects that may be returned.
        - in: query
          name: name
          schema:
            type: string
          description: Filter results by ledger name.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  self:
                    type: string
                    description: Absolute path to the collection.
                  items:
                    type: array
                    description: List of ledgers
                    items:
                      title: Ledger information links
                      description: Links to ledger information as returned by the REST APIs.
                      type: object
                      properties:
                        ledgerInfoId:
                          type: string
                          description: Hexadecimal Ledger Info ID.
                        href:
                          type: string
                          description: URL to the LedgerInfo resource.
                  total:
                    type: integer
                    description: Total number of items accross all pages.
                  pageSize:
                    type: integer
                    description: Number of items to be returned per page.
                  links:
                    $ref: "#/components/schemas/Links"
              examples:
                "[test] Success":
                  value:
                    self: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/ledgers?page[after]=1&page[size]=10
                    items:
                      - ledgerInfoId: "0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57"
                        href: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/ledgers/0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57
                      - ledgerInfoId: "0x0cd81662c95df9643238abdbfc15b6f23c7754fcb8d1cc6be909e2525b550b44"
                        href: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/ledgers/0x0cd81662c95df9643238abdbfc15b6f23c7754fcb8d1cc6be909e2525b550b44
                    total: 2
                    pageSize: 10
                    links:
                      first: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/ledgers?page[after]=1&page[size]=10
                      prev: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/ledgers?page[after]=1&page[size]=10
                      next: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/ledgers?page[after]=1&page[size]=10
                      last: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/ledgers?page[after]=1&page[size]=10
                "[pilot] Success":
                  value:
                    self: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/ledgers?page[after]=1&page[size]=10
                    items:
                      - ledgerInfoId: "0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57"
                        href: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/ledgers/0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57
                      - ledgerInfoId: "0x0cd81662c95df9643238abdbfc15b6f23c7754fcb8d1cc6be909e2525b550b44"
                        href: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/ledgers/0x0cd81662c95df9643238abdbfc15b6f23c7754fcb8d1cc6be909e2525b550b44
                    total: 2
                    pageSize: 10
                    links:
                      first: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/ledgers?page[after]=1&page[size]=10
                      prev: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/ledgers?page[after]=1&page[size]=10
                      next: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/ledgers?page[after]=1&page[size]=10
                      last: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/ledgers?page[after]=1&page[size]=10
        "400":
          description: Bad Request Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Bad Paging Request:
                  value:
                    title: Bad Paging Request
                    status: 400
                    detail: PageSize should not be greater than 50
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /trusted-ledgers-smart-contracts-registry/v2/ledgers/{ledgerInfoId}:
    get:
      operationId: get-trusted-ledgers-smart-contracts-registry-v2-ledger
      summary: Get a ledger info
      description: Returns a trusted ledger info identified by its ID.
      tags:
        - Ledgers
      parameters:
        - name: ledgerInfoId
          in: path
          schema:
            type: string
          examples:
            "[test] ledgerInfoId":
              description: valid test ledgerInfoId
              value: "0x50c4e3d7e0e9c588c0ab7b72747b10bdeab48efa9e375bf9e9b67fe91a0c64f2"
            "[pilot] ledgerInfoId":
              description: valid preprod ledgerInfoId
              value: "0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57"
          required: true
      responses:
        "200":
          description: Success
          content:
            application/ld+json:
              schema:
                type: object
              examples:
                Success:
                  value:
                    "@context": ebsi.eu
                    name: EBSI-Ethereum
                    type: ledger
                    status: active
                    protocol: eth
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {ledgerInfoId} Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: The format of {ledgerInfoId} parameter is not valid
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                LedgerInfo Not Found:
                  $ref: "#/components/examples/NotFound"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /trusted-ledgers-smart-contracts-registry/v2/ledgers/{ledgerInfoId}/revisions:
    get:
      operationId: get-trusted-ledgers-smart-contracts-registry-v2-ledger-revisions
      summary: List revisions
      description: Returns a list of revisions for a specific LedgerInfo.
      tags:
        - Ledgers
      parameters:
        - name: ledgerInfoId
          in: path
          schema:
            type: string
          examples:
            "[test] ledgerInfoId":
              description: valid test ledgerInfoId
              value: "0x50c4e3d7e0e9c588c0ab7b72747b10bdeab48efa9e375bf9e9b67fe91a0c64f2"
            "[pilot] ledgerInfoId":
              description: valid preprod ledgerInfoId
              value: "0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57"
          required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  self:
                    type: string
                    description: Absolute path to the collection.
                  items:
                    type: array
                    description: List of ledgers
                    items:
                      title: Ledger information revision links
                      description: Links to revisions as returned by the REST APIs.
                      type: object
                      properties:
                        revisionHash:
                          type: string
                          description: Hexadecimal hash of the revision.
                        href:
                          type: string
                          description: URL to the revision resource.
                  total:
                    type: integer
                    description: Total number of items accross all pages.
                  pageSize:
                    type: integer
                    description: Number of items to be returned per page.
                  links:
                    $ref: "#/components/schemas/Links"
              examples:
                "[test] Success":
                  value:
                    self: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/ledgers/0x50c4e3d7e0e9c588c0ab7b72747b10bdeab48efa9e375bf9e9b67fe91a0c64f2/revisions?page[after]=1&page[size]=10
                    items:
                      - revisionHash: "0x50c4e3d7e0e9c588c0ab7b72747b10bdeab48efa9e375bf9e9b67fe91a0c64f2"
                        href: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/ledgers/0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57/revisions/0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57
                    total: 1
                    pageSize: 10
                    links:
                      first: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/ledgers/0x50c4e3d7e0e9c588c0ab7b72747b10bdeab48efa9e375bf9e9b67fe91a0c64f2/revisions?page[after]=1&page[size]=10
                      prev: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/ledgers/0x50c4e3d7e0e9c588c0ab7b72747b10bdeab48efa9e375bf9e9b67fe91a0c64f2/revisions?page[after]=1&page[size]=10
                      next: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/ledgers/0x50c4e3d7e0e9c588c0ab7b72747b10bdeab48efa9e375bf9e9b67fe91a0c64f2/revisions?page[after]=1&page[size]=10
                      last: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/ledgers/0x50c4e3d7e0e9c588c0ab7b72747b10bdeab48efa9e375bf9e9b67fe91a0c64f2/revisions?page[after]=1&page[size]=10
                "[pilot] Success":
                  value:
                    self: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/ledgers/0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57/revisions?page[after]=1&page[size]=10
                    items:
                      - revisionHash: "0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57"
                        href: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/ledgers/0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57/revisions/0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57
                    total: 1
                    pageSize: 10
                    links:
                      first: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/ledgers/0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57/revisions?page[after]=1&page[size]=10
                      prev: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/ledgers/0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57/revisions?page[after]=1&page[size]=10
                      next: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/ledgers/0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57/revisions?page[after]=1&page[size]=10
                      last: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/ledgers/0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57/revisions?page[after]=1&page[size]=10
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {ledgerInfoId} Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: The format of {ledgerInfoId} parameter is not valid
                Bad Paging Request:
                  value:
                    title: Bad Paging Request
                    status: 400
                    detail: PageSize should not be greater than 50
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                LedgerInfo Not Found:
                  $ref: "#/components/examples/NotFound"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /trusted-ledgers-smart-contracts-registry/v2/ledgers/{ledgerInfoId}/revisions/{revisionHash}:
    get:
      operationId: get-trusted-ledgers-smart-contracts-registry-v2-ledger-revision
      summary: Get a revision
      description: Returns the revision corresponding to the given hash.
      tags:
        - Ledgers
      parameters:
        - name: ledgerInfoId
          in: path
          schema:
            type: string
          examples:
            "[test] ledgerInfoId":
              description: valid test ledgerInfoId
              value: "0x50c4e3d7e0e9c588c0ab7b72747b10bdeab48efa9e375bf9e9b67fe91a0c64f2"
            "[pilot] ledgerInfoId":
              description: valid preprod ledgerInfoId
              value: "0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57"
          required: true
        - name: revisionHash
          in: path
          schema:
            type: string
          examples:
            "[test] revisionHash":
              description: valid test revisionHash
              value: "0x50c4e3d7e0e9c588c0ab7b72747b10bdeab48efa9e375bf9e9b67fe91a0c64f2"
            "[pilot] revisionHash":
              description: valid preprod revisionHash
              value: "0xc981798c566a266b48cfd0d7684a4a00ce8d9d9d770aa7614ff0f7cc724e0a57"
          required: true
      responses:
        "200":
          description: Success
          content:
            application/ld+json:
              schema:
                type: object
              examples:
                Success:
                  value:
                    "@context": ebsi.eu
                    name: EBSI-Ethereum
                    type: ledger
                    status: active
                    protocol: eth
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {ledgerInfoId} Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: The format of {ledgerInfoId} parameter is not valid
                Invalid {revisionHash} Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: The format of {revisionHash} parameter is not valid
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                LedgerInfo Not Found:
                  $ref: "#/components/examples/NotFound"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /trusted-ledgers-smart-contracts-registry/v2/smart-contracts:
    get:
      operationId: get-trusted-ledgers-smart-contracts-registry-v2-smart-contracts
      summary: List smart contracts
      description: Returns a list of smart contracts.
      tags:
        - Smart Contracts
      parameters:
        - in: query
          name: page[after]
          schema:
            type: string
          description: Cursor that points to the end of the page of data that has been returned.
        - schema:
            type: integer
          in: query
          name: page[size]
          description: Defines the maximum number of objects that may be returned.
        - in: query
          name: name
          schema:
            type: string
          description: Filter results by smart contract name.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  self:
                    type: string
                    description: Absolute path to the collection.
                  items:
                    type: array
                    description: List of ledgers
                    items:
                      title: Smart contract information links
                      description: Links to smart contract information as returned by the REST APIs.
                      type: object
                      properties:
                        smartContractInfoId:
                          type: string
                          description: Hexadecimal smart contract info ID.
                        href:
                          type: string
                          description: URL to the SmartContractInfo resource.
                  total:
                    type: integer
                    description: Total number of items accross all pages.
                  pageSize:
                    type: integer
                    description: Number of items to be returned per page.
                  links:
                    $ref: "#/components/schemas/Links"
              examples:
                "[test] Success":
                  value:
                    self: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts?page[after]=1&page[size]=10
                    items:
                      - smartContractInfoId: "0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed"
                        href: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed
                      - smartContractInfoId: "0x2bcd6e0ff362b35b9cd510a0f1deaaeda18cfa0a3f20d477b738c57d506e0da9"
                        href: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0x2bcd6e0ff362b35b9cd510a0f1deaaeda18cfa0a3f20d477b738c57d506e0da9
                      - smartContractInfoId: "0x72d1f36bffd10b2760b6c57da3c886d39689e04a23b5a75d3be6ad2e99195d7e"
                        href: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0x72d1f36bffd10b2760b6c57da3c886d39689e04a23b5a75d3be6ad2e99195d7e
                      - smartContractInfoId: "0x63117ba242c0bd812b689200e0f80e805cbc13feb351aa20798e8fb8d5a7ddea"
                        href: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0x63117ba242c0bd812b689200e0f80e805cbc13feb351aa20798e8fb8d5a7ddea
                      - smartContractInfoId: "0xf8e665a36a7e87846b0cc64abf03454c5a3f2c201b66ac8bbc96d7dea44c9f0c"
                        href: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xf8e665a36a7e87846b0cc64abf03454c5a3f2c201b66ac8bbc96d7dea44c9f0c
                      - smartContractInfoId: "0xf09fb81d126b8b0b11e7be8e096cf7f2c2421c53e860b07f46c46f3c7dd50f93"
                        href: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xf09fb81d126b8b0b11e7be8e096cf7f2c2421c53e860b07f46c46f3c7dd50f93
                    total: 6
                    pageSize: 10
                    links:
                      first: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts?page[after]=1&page[size]=10
                      prev: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts?page[after]=1&page[size]=10
                      next: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts?page[after]=1&page[size]=10
                      last: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts?page[after]=1&page[size]=10
                "[pilot] Success":
                  value:
                    self: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts?page[after]=1&page[size]=10
                    items:
                      - smartContractInfoId: "0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed"
                        href: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed
                      - smartContractInfoId: "0x2bcd6e0ff362b35b9cd510a0f1deaaeda18cfa0a3f20d477b738c57d506e0da9"
                        href: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0x2bcd6e0ff362b35b9cd510a0f1deaaeda18cfa0a3f20d477b738c57d506e0da9
                      - smartContractInfoId: "0x72d1f36bffd10b2760b6c57da3c886d39689e04a23b5a75d3be6ad2e99195d7e"
                        href: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0x72d1f36bffd10b2760b6c57da3c886d39689e04a23b5a75d3be6ad2e99195d7e
                      - smartContractInfoId: "0x63117ba242c0bd812b689200e0f80e805cbc13feb351aa20798e8fb8d5a7ddea"
                        href: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0x63117ba242c0bd812b689200e0f80e805cbc13feb351aa20798e8fb8d5a7ddea
                      - smartContractInfoId: "0xf8e665a36a7e87846b0cc64abf03454c5a3f2c201b66ac8bbc96d7dea44c9f0c"
                        href: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xf8e665a36a7e87846b0cc64abf03454c5a3f2c201b66ac8bbc96d7dea44c9f0c
                      - smartContractInfoId: "0xf09fb81d126b8b0b11e7be8e096cf7f2c2421c53e860b07f46c46f3c7dd50f93"
                        href: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xf09fb81d126b8b0b11e7be8e096cf7f2c2421c53e860b07f46c46f3c7dd50f93
                    total: 6
                    pageSize: 10
                    links:
                      first: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts?page[after]=1&page[size]=10
                      prev: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts?page[after]=1&page[size]=10
                      next: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts?page[after]=1&page[size]=10
                      last: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts?page[after]=1&page[size]=10
        "400":
          description: Bad Request Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Bad Paging Request:
                  value:
                    title: Bad Paging Request
                    status: 400
                    detail: PageSize should not be greater than 50
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /trusted-ledgers-smart-contracts-registry/v2/smart-contracts/{smartContractInfoId}:
    get:
      operationId: get-trusted-ledgers-smart-contracts-registry-v2-smart-contract
      summary: Get a smart contract info
      description: Returns a trusted smart contract info identified by its ID.
      tags:
        - Smart Contracts
      parameters:
        - name: smartContractInfoId
          in: path
          schema:
            type: string
          examples:
            "[test] smartContractInfoId":
              description: valid test smartContractInfoId
              value: "0xfc9d8ef5bbf1d9caa668a42c11120a4a5270cd5268ce0b0764759bc8e3990d28"
            "[pilot] smartContractInfoId":
              description: valid preprod smartContractInfoId
              value: "0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed"
          required: true
      responses:
        "200":
          description: Success
          content:
            application/ld+json:
              schema:
                type: object
              examples:
                Success:
                  value:
                    "@context": ebsi.eu
                    name: Timestamp Registry Smart Contract
                    blockchainProtocol: eth
                    EBSILedgerName: EBSI-Ethereum
                    smartContractDetails:
                      address: "0xC892CB012E2efe16f8CcDb0a7e706BFa060c2e8a"
                      type: Registry
                      status: active
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {smartContractInfoId} Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: The format of {smartContractInfoId} parameter is not valid
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                SmartContractInfo Not Found:
                  $ref: "#/components/examples/NotFound"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /trusted-ledgers-smart-contracts-registry/v2/smart-contracts/{smartContractInfoId}/revisions:
    get:
      operationId: get-trusted-ledgers-smart-contracts-registry-v2-smart-contract-revisions
      summary: List revisions
      description: Returns a list of revisions for a specific SmartContractInfo.
      tags:
        - Smart Contracts
      parameters:
        - name: smartContractInfoId
          in: path
          schema:
            type: string
          examples:
            "[test] smartContractInfoId":
              description: valid test smartContractInfoId
              value: "0xfc9d8ef5bbf1d9caa668a42c11120a4a5270cd5268ce0b0764759bc8e3990d28"
            "[pilot] smartContractInfoId":
              description: valid preprod smartContractInfoId
              value: "0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed"
          required: true
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  self:
                    type: string
                    description: Absolute path to the collection.
                  items:
                    type: array
                    description: List of ledgers
                    items:
                      title: Smart contract information revision links
                      description: Links to revisions as returned by the REST APIs.
                      type: object
                      properties:
                        revisionHash:
                          type: string
                          description: Hexadecimal hash of the revision.
                        href:
                          type: string
                          description: URL to the revision resource.
                  total:
                    type: integer
                    description: Total number of items accross all pages.
                  pageSize:
                    type: integer
                    description: Number of items to be returned per page.
                  links:
                    $ref: "#/components/schemas/Links"
              examples:
                "[test] Success":
                  value:
                    self: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed/revisions?page[after]=1&page[size]=10
                    items:
                      - revisionHash: "0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed"
                        href: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed/revisions/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed
                    total: 1
                    pageSize: 10
                    links:
                      first: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed/revisions?page[after]=1&page[size]=10
                      prev: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed/revisions?page[after]=1&page[size]=10
                      next: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed/revisions?page[after]=1&page[size]=10
                      last: https://test.intebsi.xyz/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed/revisions?page[after]=1&page[size]=10
                "[pilot] Success":
                  value:
                    self: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed/revisions?page[after]=1&page[size]=10
                    items:
                      - revisionHash: "0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed"
                        href: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed/revisions/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed
                    total: 1
                    pageSize: 10
                    links:
                      first: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed/revisions?page[after]=1&page[size]=10
                      prev: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed/revisions?page[after]=1&page[size]=10
                      next: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed/revisions?page[after]=1&page[size]=10
                      last: https://api.preprod.ebsi.eu/trusted-ledgers-smart-contracts-registry/v2/smart-contracts/0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed/revisions?page[after]=1&page[size]=10
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {smartContractInfoId} Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: The format of {smartContractInfoId} parameter is not valid
                Bad Paging Request:
                  value:
                    title: Bad Paging Request
                    status: 400
                    detail: PageSize should not be greater than 50
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                LedgerInfo Not Found:
                  $ref: "#/components/examples/NotFound"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /trusted-ledgers-smart-contracts-registry/v2/smart-contracts/{smartContractInfoId}/revisions/{revisionHash}:
    get:
      operationId: get-trusted-ledgers-smart-contracts-registry-v2-smart-contract-revision
      summary: Get a revision
      description: Returns the revision corresponding to the given hash.
      tags:
        - Smart Contracts
      parameters:
        - name: smartContractInfoId
          in: path
          schema:
            type: string
          examples:
            "[test] smartContractInfoId":
              description: valid test smartContractInfoId
              value: "0xfc9d8ef5bbf1d9caa668a42c11120a4a5270cd5268ce0b0764759bc8e3990d28"
            "[pilot] smartContractInfoId":
              description: valid preprod smartContractInfoId
              value: "0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed"
          required: true
        - name: revisionHash
          in: path
          schema:
            type: string
          examples:
            "[test] revisionHash":
              description: valid test revisionHash
              value: "0xfc9d8ef5bbf1d9caa668a42c11120a4a5270cd5268ce0b0764759bc8e3990d28"
            "[pilot] revisionHash":
              description: valid preprod revisionHash
              value: "0xd4cf294b16f142479ab2b6405ede4910638541aca3c1a77cf95e9e16542743ed"
          required: true
      responses:
        "200":
          description: Success
          content:
            application/ld+json:
              schema:
                type: object
              examples:
                Success:
                  value:
                    "@context": ebsi.eu
                    name: Timestamp Registry Smart Contract
                    blockchainProtocol: eth
                    EBSILedgerName: EBSI-Ethereum
                    smartContractDetails:
                      address: "0xC892CB012E2efe16f8CcDb0a7e706BFa060c2e8a"
                      type: Registry
                      status: active
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Invalid {smartContractInfoId} Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: The format of {smartContractInfoId} parameter is not valid
                Invalid {revisionHash} Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: The format of {revisionHash} parameter is not valid
        "404":
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                LedgerInfo Not Found:
                  $ref: "#/components/examples/NotFound"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
  /trusted-ledgers-smart-contracts-registry/v2/jsonrpc:
    post:
      operationId: post-trusted-ledgers-smart-contracts-registry-v2-jsonrpc
      summary: JSON-RPC API
      description: |
        The JSON-RPC API provides methods assisting the construction of blockchain transactions and
        interaction with the ledger.
      tags:
        - JSON-RPC
      security:
        - bearerAuth: []
      requestBody:
        required: true
        description: |
          The body follows the
          [JSON-RPC 2.0 specification](https://www.jsonrpc.org/specification).

          It requires the following fields:

          - **jsonrpc**: must be exactly "2.0"
          - **method**: method to be invoked
          - **params**: method parameters
          - **id**: identifier established by the client

          ### API Methods

          #### insertLedgerInfo

          Call to build an unsigned transaction to insert ledger info in the registry. This method
          requires admin rights in the Trusted Policies Registry.

          Parameters:
          - **from**: Ethereum address of the administrator
          - **name**: Name for the new ledger
          - **info**: Data information. This field must be a JSON stringified and converted into hex string.

          #### updateLedgerInfoById

          Call to build an unsigned transaction to update a ledger info in the registry given its
          ID. This method requires admin rights in the Trusted Policies Registry.

          Parameters:
          - **from**: Ethereum address of the administrator
          - **ledgerInfoId**: Ledger Info ID
          - **info**: Data information. This field must be a JSON stringified and converted into hex string.

          #### updateLedgerInfoByName

          Call to build an unsigned transaction to update a ledger info in the registry given its
          name. This method requires admin rights in the Trusted Policies Registry.

          Parameters:
          - **from**: Ethereum address of the administrator
          - **name**: Name of the ledger
          - **info**: Data information. This field must be a JSON stringified and converted into hex string.

          #### updateLedgerName

          Call to build an unsigned transaction to update the name of a ledger. This method
          requires admin rights in the Trusted Policies Registry.

          Parameters:
          - **from**: Ethereum address of the administrator
          - **oldName**: Previous name
          - **newName**: New name

          #### insertSmartContractInfo

          Call to build an unsigned transaction to insert smart contract info in the registry. This
          method requires admin rights in the Trusted Policies Registry.

          Parameters:
          - **from**: Ethereum address of the administrator
          - **name**: Name for the new smart contract
          - **info**: Data information. This field must be a JSON stringified and converted into hex string.

          #### updateSmartContractInfoById

          Call to build an unsigned transaction to update a smart contract info in the registry
          given its ID. This method requires admin rights in the Trusted Policies Registry.

          Parameters:
          - **from**: Ethereum address of the administrator
          - **smartContractInfoId**: Smart Contract Info ID
          - **info**: Data information. This field must be a JSON stringified and converted into hex string.

          #### updateSmartContractInfoByName

          Call to build an unsigned transaction to update a smart contract info in the registry
          given its name. This method requires admin rights in the Trusted Policies Registry.

          Parameters:
          - **from**: Ethereum address of the administrator
          - **name**: Name of the smart contract
          - **info**: Data information. This field must be a JSON stringified and converted into hex string.

          #### updateSmartContractName

          Call to build an unsigned transaction to update the name of a smart contract. This method requires admin rights in the Trusted Policies Registry.

          Parameters:
          - **from**: Ethereum address of the administrator
          - **oldName**: Previous name
          - **newName**: New name

          #### sendSignedTransaction

          Call to send a signed transaction to the blockchain.
        content:
          application/json:
            schema:
              required:
                - jsonrpc
                - id
                - method
                - params
              type: object
              properties:
                jsonrpc:
                  description: Must be exactly "2.0"
                  type: string
                method:
                  description: Method that needs to be invoked
                  type: string
                params:
                  description: Array of parameters
                  type: array
                  items:
                    type: object
                id:
                  description: Identifier established by the client
                  type: integer
                  example: 1
            examples:
              Build tx to insertLedgerInfo:
                value:
                  jsonrpc: "2.0"
                  method: insertLedgerInfo
                  id: 1
                  params:
                    - from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                      name: EBSI Ethereum
                      info: "0x7b226e616d65223a224542534920657468657265756d227d"
              Build tx to updateLedgerInfoById:
                value:
                  jsonrpc: "2.0"
                  method: updateLedgerInfoById
                  id: 1
                  params:
                    - from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                      ledgerInfoId: "0x94df19c1c654f4bca27545c2ab06647bb96356c4b771a6af0aa54b7bb8f6ffb7"
                      info: "0x7b226e616d65223a224542534920657468657265756d227d"
              Build tx to updateLedgerInfoByName:
                value:
                  jsonrpc: "2.0"
                  method: updateLedgerInfoByName
                  id: 1
                  params:
                    - from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                      name: EBSI Ethereum
                      info: "0x7b226e616d65223a224542534920657468657265756d227d"
              Build tx to updateLedgerName:
                value:
                  jsonrpc: "2.0"
                  method: updateLedgerName
                  id: 1
                  params:
                    - from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                      oldName: EBSI Ethereum
                      newName: EBSI Ethereum 2
              Build tx to insertSmartContractInfo:
                value:
                  jsonrpc: "2.0"
                  method: insertSmartContractInfo
                  id: 1
                  params:
                    - from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                      name: Trusted Issuers Registry Smart Contract
                      info: "0x7b226e616d65223a226d7920636f6e7472616374227d"
              Build tx to updateSmartContractInfoById:
                value:
                  jsonrpc: "2.0"
                  method: updateSmartContractInfoById
                  id: 1
                  params:
                    - from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                      smartContractInfoId: "0x94df19c1c654f4bca27545c2ab06647bb96356c4b771a6af0aa54b7bb8f6ffb7"
                      info: "0x7b226e616d65223a226d7920636f6e7472616374227d"
              Build tx to updateSmartContractInfoByName:
                value:
                  jsonrpc: "2.0"
                  method: updateSmartContractInfoByName
                  id: 1
                  params:
                    - from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                      name: EBSI Ethereum
                      info: "0x7b226e616d65223a226d7920636f6e7472616374227d"
              Build tx to updateSmartContractName:
                value:
                  jsonrpc: "2.0"
                  method: updateSmartContractName
                  id: 1
                  params:
                    - from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                      oldName: timesmp-sc-ethereum
                      newName: timestamp-sc-ethereum
              Send Transaction:
                description: Call to send a signed transaction to the blockchain.
                value:
                  jsonrpc: "2.0"
                  method: sendSignedTransaction
                  id: 1
                  params:
                    - protocol: eth
                      unsignedTransaction:
                        from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                        to: "0xFde86148db58f57787C06BeAf63a9c3f789357b3"
                        data: "0x0000..."
                        nonce: "0x00"
                        chainId: "0x1b3b"
                        gasLimit: "0x10000"
                        gasPrice: "0x00"
                        value: "0x00"
                      r: "0x..."
                      s: "0x..."
                      v: "0x..."
                      signedRawTransaction: "--- signed raw transaction ---"
              Send Transaction (DEPRECATED):
                description: |
                  THIS METHOD IS DEPRECATED! Use "sendSignedTransaction" instead.
                  Call to send a signed transaction to the blockchain.
                value:
                  jsonrpc: "2.0"
                  method: signedTransaction
                  id: 1
                  params:
                    - protocol: eth
                      unsignedTransaction:
                        from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                        to: "0xFde86148db58f57787C06BeAf63a9c3f789357b3"
                        data: "0x0000..."
                        nonce: "0x00"
                        chainId: "0x1b3b"
                        gasLimit: "0x10000"
                        gasPrice: "0x00"
                        value: "0x00"
                      r: "0x..."
                      s: "0x..."
                      v: "0x..."
                      signedRawTransaction: "--- signed raw transaction ---"
      responses:
        "200":
          description: Response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JsonRpcResponse"
              examples:
                Build tx:
                  value:
                    jsonrpc: "2.0"
                    id: 1
                    result:
                      from: "0x416e6e6162656c2e4c65652e452d412d506f652e"
                      to: "0xFde86148db58f57787C06BeAf63a9c3f789357b3"
                      data: "0x0000..."
                      nonce: "0x00"
                      chainId: "0x1b3b"
                      gasLimit: "0x10000"
                      gasPrice: "0x00"
                      value: "0x00"
                Send Transaction:
                  value:
                    jsonrpc: "2.0"
                    id: 1
                    result: "0xe670ec64341771606e55d6b4ca35a1a6b75ee3d5145a99d05921026d1527331"
        "400":
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              examples:
                Bad Request:
                  $ref: "#/components/examples/BadRequest"
components:
  schemas:
    ProblemDetails:
      title: Problem Details
      description: A [Problem Details](https://datatracker.ietf.org/doc/html/rfc7807) object.
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced,
            it SHOULD provide human-readable documentation for the problem type.
          default: about:blank
        title:
          type: string
          description: |
            A short summary of the problem type.
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem.
          example: Connection timeout
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.
    Links:
      title: Links
      type: object
      description: Links model used for pagination.
      properties:
        first:
          type: string
          description: Hyperlink to the first page.
        prev:
          type: string
          description: Hyperlink to the previous page.
        next:
          type: string
          description: Hyperlink to the next page.
        last:
          type: string
          description: Hyperlink to the last page.
    JsonRpcResponse:
      title: JSON-RPC Response
      type: object
      properties:
        jsonrpc:
          description: Must be exactly "2.0"
          type: string
        id:
          description: Same identifier established by the client in the call
          type: integer
        result:
          description: Result of the call
          oneOf:
            - type: object
            - type: string
  examples:
    BadRequest:
      value:
        title: Bad Request
        status: 400
        detail: Bad request
    NotFound:
      value:
        title: Not found
        status: 404
        detail: Not found
    InternalError:
      value:
        title: Internal error
        status: 500
        detail: Internal error
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
servers:
  - url: "http://localhost"
    description: Local Computer Environment
  - url: "https://api.preprod.ebsi.eu"
    description: EBSI Pre-production Environment
  - url: "https://api.ebsi.eu"
    description: EBSI Production Environment
