openapi: 3.0.3
info:
  title: Notifications API
  version: 1.0.0
  description: |
    Notifications API is an EBSI core service that helps to send async or delayed notifications by
    addressing the DID of a natural person or legal entity.

    * Notification service can be used by any entity/user registered in the DID registry or
    application registered in the Trusted Applications Registry (TAR).
    * Entity or application is notified via its DID registered in the DID registry or TAR.

    For more information see:
    * [Technical Specifications](https://ec.europa.eu/cefdigital/wiki/display/EBSIDOC/Notifications+API)
    * [Code repository](https://ec.europa.eu/cefdigital/code/projects/EBSI/repos/notifications-api/)
  termsOfService: /docs/terms
  contact:
    name: EBSI Support – Service Desk
    url: https://ec.europa.eu/cefdigital/tracker/plugins/servlet/desk/portal/11
  license:
    name: EUPL-1.2
    url: https://joinup.ec.europa.eu/page/eupl-text-11-12
servers:
  - url: http://localhost
    description: Local Computer Environment
  - url: https://api.preprod.ebsi.eu
    description: EBSI Pre-production Environment
  - url: https://api.ebsi.eu
    description: EBSI Production Environment
tags:
  - name: Notifications
    description: Store and retrieve notifications
paths:
  /notifications/v1/notifications:
    post:
      tags:
        - Notifications
      summary: Create a new notification
      description: Creates a new notification and stores it to the Decentralized Storage.
      parameters:
        - $ref: "#/components/parameters/headerConformance"
      operationId: post-notifications-v1-notifications
      security:
        - bearerAuth: []
      requestBody:
        description: |
          Notification Request Input

          [EBSI conformance testing](https://ec.europa.eu/cefdigital/wiki/x/5YDwG) The API supports
          the following EBSI conformance tests:
          * Transfer Verifiable Authorisation (CT V1 ONBOARD_04_B)
          * Request Verifiable Attestation (CT V1 ISSUE_011)
          * Transfer Verifiable Attestation (CT V1 ISSUE_031)
          * Transfer Verifiable Presentation (CT V1 VERIFY_031)
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Notification"
            examples:
              New Notification:
                value:
                  schemaId: notification-001
                  type:
                    - Notification
                    - StoreVerifiableCredential
                  "@context":
                    - https://www.w3.org/2018/credentials/v1
                    - https://essif.europa.eu/schemas/vc/2020/v1
                    - https://essif.europa.eu/schemas/notifications/2020/v1
                  from: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
                  to: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ
                  issuanceDate: "2019-06-22T14:11:44Z"
                  expirationDate: "2019-06-27T14:11:44Z"
                  payload: {}
                  proof:
                    type: EcdsaSecp256k1Signature2019
                    created: "2019-11-17T14:00:00Z"
                    proofPurpose: assertionMethod
                    verificationMethod: did:ebsi:zub5ZZUfHLLptCduwEy8xRj#key-1
                    jws: eyJh..Iw
              ct_ONBOARD_04_B:
                summary: Transfer Verifiable Authorisation  (CT V1 ONBOARD_04_B)
                description: |
                  This is test data for [CT V1 ONBOARD_04_B](https://ec.europa.eu/cefdigital/wiki/display/BLOCKCHAININT/RFC+-+Conformance+testing#RFCConformancetesting-Scenario:ONBOARD).
                  'payload' is a properly formed verifiable Authorisation.
                value:
                  schemaId: notification-001
                  type:
                    - Notification
                    - StoreVerifiableAuthorisation
                  "@context":
                    - https://www.w3.org/2018/credentials/v1
                    - https://essif.europa.eu/schemas/vc/2020/v1
                    - https://essif.europa.eu/schemas/notifications/2020/v1
                  from: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
                  to: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ
                  issuanceDate: "2019-06-22T14:11:44Z"
                  expirationDate: "2019-06-27T14:11:44Z"
                  payload:
                    verifiableCredential:
                      id: vc:ebsi:authentication#bfc64c03-a203-4005-8ce7-9593d1421636
                      issuer: did:ebsi:zwC56DZdiJh8kSxbgg4fMCu
                      validFrom: "2021-10-12T09:44:01Z"
                      credentialSubject:
                        id: did:ebsi:zctk4PzNdbyCzKWwV5VZh3t
                      credentialSchema:
                        id: https://api.test.intebsi.xyz/trusted-schemas-registry/v1/schemas/0x312e332e362e312e342e312e313338312e332e31322e332e322e332e3738
                        type: OID
                      issuanceDate: "2021-10-12T09:44:01Z"
                      expirationDate: "2022-04-12T09:44:01Z"
                      "@context":
                        - https://www.w3.org/2018/credentials/v1
                        - https://www.w3.org/2018/credentials/examples/v1
                        - https://w3c-ccg.github.io/lds-jws2020/contexts/lds-jws2020-v1.json
                      type:
                        - VerifiableCredential
                        - VerifiableAuthorisation
                      proof:
                        type: EcdsaSecp256k1Signature2019
                        created: "2021-10-12T09:44:01Z"
                        proofPurpose: assertionMethod
                        verificationMethod: did:ebsi:zwC56DZdiJh8kSxbgg4fMCu#keys-1
                        jws: eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QifQ..XzsjuUGM8Z8iGEn_s9sS4MbsHBxnEmYBvnn3BTc6tUig9e_1FIBPtE8Fgs8UM6HKeHGYOrY-_0rm8vT3zh_X3Q
                  proof:
                    type: EcdsaSecp256k1Signature2019
                    created: "2019-11-17T14:00:00Z"
                    proofPurpose: assertionMethod
                    verificationMethod: did:ebsi:zub5ZZUfHLLptCduwEy8xRj#key-1
                    jws: eyJh..Iw
              ct_ISSUE_011:
                summary: Request Verifiable Attestation  (CT V1 ISSUE_011)
                description: |
                  This is test data for [CT V1 ISSUE_011](https://ec.europa.eu/cefdigital/wiki/display/BLOCKCHAININT/RFC+-+Conformance+testing#RFCConformancetesting-Scenario:ISSUE).
                  'payload' is a properly formed verifiable Attestation request.
                value:
                  schemaId: notification-001
                  type:
                    - Notification
                    - RequestVerifiableAttestation
                  "@context":
                    - https://www.w3.org/2018/credentials/v1
                    - https://essif.europa.eu/schemas/vc/2020/v1
                    - https://essif.europa.eu/schemas/notifications/2020/v1
                  from: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
                  to: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ
                  issuanceDate: "2019-06-22T14:11:44Z"
                  expirationDate: "2019-06-27T14:11:44Z"
                  payload: {}
                  proof:
                    type: EcdsaSecp256k1Signature2019
                    created: "2019-11-17T14:00:00Z"
                    proofPurpose: assertionMethod
                    verificationMethod: did:ebsi:zub5ZZUfHLLptCduwEy8xRj#key-1
                    jws: eyJh..Iw
              ct_ISSUE_031:
                summary: Transfer Verifiable Attestation  (CT V1 ISSUE_031)
                description: |
                  This is test data for [CT V1 ISSUE_031](https://ec.europa.eu/cefdigital/wiki/display/BLOCKCHAININT/RFC+-+Conformance+testing#RFCConformancetesting-Scenario:ISSUE).
                  'payload' is a properly formed verifiable Attestation.
                value:
                  schemaId: notification-001
                  type:
                    - Notification
                    - StoreVerifiableAttestation
                  "@context":
                    - https://www.w3.org/2018/credentials/v1
                    - https://essif.europa.eu/schemas/vc/2020/v1
                    - https://essif.europa.eu/schemas/notifications/2020/v1
                  from: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
                  to: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ
                  issuanceDate: "2019-06-22T14:11:44Z"
                  expirationDate: "2019-06-27T14:11:44Z"
                  payload:
                    verifiableCredential:
                      id: vc:ebsi:attestation#bfc64c03-a203-4005-8ce7-9593d1421636
                      issuer: did:ebsi:zwC56DZdiJh8kSxbgg4fMCu
                      validFrom: "2021-10-12T09:44:01Z"
                      credentialSubject:
                        id: did:ebsi:zctk4PzNdbyCzKWwV5VZh3t
                      credentialSchema:
                        id: https://api.test.intebsi.xyz/trusted-schemas-registry/v1/schemas/0x312e332e362e312e342e312e313338312e332e31322e332e322e332e3738
                        type: OID
                      issuanceDate: "2021-10-12T09:44:01Z"
                      expirationDate: "2022-04-12T09:44:01Z"
                      "@context":
                        - https://www.w3.org/2018/credentials/v1
                        - https://www.w3.org/2018/credentials/examples/v1
                        - https://w3c-ccg.github.io/lds-jws2020/contexts/lds-jws2020-v1.json
                      type:
                        - VerifiableCredential
                        - VerifiableAttestation
                      proof:
                        type: EcdsaSecp256k1Signature2019
                        created: "2021-10-12T09:44:01Z"
                        proofPurpose: assertionMethod
                        verificationMethod: did:ebsi:zwC56DZdiJh8kSxbgg4fMCu#keys-1
                        jws: eyJhbGciOiJFUzI1NksiLCJ0eXAiOiJKV1QifQ..XzsjuUGM8Z8iGEn_s9sS4MbsHBxnEmYBvnn3BTc6tUig9e_1FIBPtE8Fgs8UM6HKeHGYOrY-_0rm8vT3zh_X3Q
                  proof:
                    type: EcdsaSecp256k1Signature2019
                    created: "2019-11-17T14:00:00Z"
                    proofPurpose: assertionMethod
                    verificationMethod: did:ebsi:zub5ZZUfHLLptCduwEy8xRj#key-1
                    jws: eyJh..Iw
              ct_VERIFY_031:
                summary: Transfer Verifiable Presentation  (CT V1 VERIFY_031)
                description: |
                  This is test data for [CT V1 VERIFY_031](https://ec.europa.eu/cefdigital/wiki/display/BLOCKCHAININT/RFC+-+Conformance+testing#RFCConformancetesting-Scenario:VERIFY).
                  'payload' is a properly formed verifiable presentation.
                value:
                  schemaId: notification-001
                  type:
                    - Notification
                    - StoreVerifiablePresentation
                  "@context":
                    - https://www.w3.org/2018/credentials/v1
                    - https://essif.europa.eu/schemas/vc/2020/v1
                    - https://essif.europa.eu/schemas/notifications/2020/v1
                  from: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
                  to: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ
                  issuanceDate: "2019-06-22T14:11:44Z"
                  expirationDate: "2019-06-27T14:11:44Z"
                  payload:
                    response_type: id_token
                    client_id: did:ebsi:1234
                    redirect_uri: https://client.example.org/cb
                    scope: openid
                    nonce: acasfir6AKqGhg
                    registration:
                      subject_identifier_types_supported:
                        - did
                      did_methods_supported:
                        - "did:ebsi:"
                      vp_formats:
                        jwt_vp:
                          alg:
                            - EdDSA
                            - ES256K
                        ldp_vp:
                          proof_type:
                            - Ed25519Signature2018
                      client_name: Example Client
                      client_purpose: DID Authentication
                      tos_uri: https://client.example.org/tos.html
                      logo_uri: https://client.example.org/images/did_logo.png
                    exp: 1311281970
                    iat: 1311280970
                    claims:
                      vp_token:
                        verifiable_presentations:
                          presentation_definition:
                            id: <definition-id>
                            input_descriptors:
                              - id: <input-id, e.g., V-ID>
                                schema:
                                  - uri: https://<base-uri>/contexts/v1/VerifiableID
                  proof:
                    type: EcdsaSecp256k1Signature2019
                    created: "2019-11-17T14:00:00Z"
                    proofPurpose: assertionMethod
                    verificationMethod: did:ebsi:zub5ZZUfHLLptCduwEy8xRj#key-1
                    jws: eyJh..Iw
        required: true
      responses:
        "201":
          description: Creates a new notification
          headers:
            Location:
              schema:
                type: string
                example: https://api.ebsi.xyz/notifications/v1/notifications/123
              description: URI to retrieve a specific notification using its identifier.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Notification"
              examples:
                Created:
                  value:
                    schemaId: notification-001
                    type:
                      - Notification
                      - StoreVerifiableCredential
                    "@context":
                      - https://www.w3.org/2018/credentials/v1
                      - https://essif.europa.eu/schemas/vc/2020/v1
                      - https://essif.europa.eu/schemas/notifications/2020/v1
                    from: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
                    to: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ
                    issuanceDate: "2019-06-22T14:11:44Z"
                    expirationDate: "2019-06-27T14:11:44Z"
                    payload: {}
                    proof:
                      type: EcdsaSecp256k1Signature2019
                      created: "2019-11-17T14:00:00Z"
                      proofPurpose: assertionMethod
                      verificationMethod: did:ebsi:zub5ZZUfHLLptCduwEy8xRj#key-1
                      jws: eyJh..Iw
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                BadRequest:
                  $ref: "#/components/examples/BadRequest"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "500":
          description: Internal Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
    get:
      tags:
        - Notifications
      summary: Get all notifications
      description: Retrieves all the notifications corresponding to the Bearer Token's DID.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "#/components/schemas/NotificationLinks"
                  self:
                    type: string
                    description: |
                      Absolute URI (http or https) to the the resource's own location.
                  links:
                    $ref: "#/components/schemas/Links"
                  pageSize:
                    type: integer
                    description: Maximum number of items per page.
                  total:
                    type: integer
                    description: Total number of items across all pages.
              examples:
                Get notifications:
                  value:
                    items:
                      - schemaId: notification-001
                        type:
                          - Notification
                          - StoreVerifiableCredential
                        "@context":
                          - https://www.w3.org/2018/credentials/v1
                          - https://essif.europa.eu/schemas/vc/2020/v1
                          - https://essif.europa.eu/schemas/notifications/2020/v1
                        from: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
                        to: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ
                        issuanceDate: "2019-06-22T14:11:44Z"
                        expirationDate: "2019-06-27T14:11:44Z"
                        payload: {}
                        proof:
                          type: EcdsaSecp256k1Signature2019
                          created: "2019-11-17T14:00:00Z"
                          proofPurpose: assertionMethod
                          verificationMethod: did:ebsi:zub5ZZUfHLLptCduwEy8xRj#key-1
                          jws: eyJh..Iw
                        _links:
                          self:
                            href: /notifications/v1/notifications/123
                      - schemaId: notification-001
                        type:
                          - Notification
                          - RequestVerifiablePresentation
                        "@context":
                          - https://www.w3.org/2018/credentials/v1
                          - https://essif.europa.eu/schemas/vc/2020/v1
                          - https://essif.europa.eu/schemas/notifications/2020/v1
                        from: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
                        to: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ
                        issuanceDate: "2019-06-22T14:11:44Z"
                        expirationDate: "2019-06-27T14:11:44Z"
                        payload: {}
                        proof:
                          type: EcdsaSecp256k1Signature2019
                          created: "2019-11-17T14:00:00Z"
                          proofPurpose: assertionMethod
                          verificationMethod: did:ebsi:zub5ZZUfHLLptCduwEy8xRj#key-1
                          jws: eyJh..Iw
                        _links:
                          self:
                            href: https://api.ebsi.xyz/notifications/v1/notifications/124
                    total: 13
                    pageSize: 2
                    self: https://api.ebsi.xyz/notifications/v1/notifications?page[after]=3&page[size]=2
                    links:
                      first: https://api.ebsi.xyz/notifications/v1/notifications?page[after]=1&page[size]=2
                      prev: https://api.ebsi.xyz/notifications/v1/notifications?page[after]=2&page[size]=2
                      next: https://api.ebsi.xyz/notifications/v1/notifications?page[after]=4&page[size]=2
                      last: https://api.ebsi.xyz/notifications/v1/notifications?page[after]=7&page[size]=2
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                BadRequest:
                  $ref: "#/components/examples/BadRequest"
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "500":
          description: Internal Server Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
      security:
        - bearerAuth: []
      operationId: get-notifications-v1-notifications
      parameters:
        - $ref: "#/components/parameters/headerConformance"
        - in: query
          name: page[before]
          schema:
            type: string
          description: |
            Cursor that points to the start of the page of data that has been returned.
        - in: query
          name: page[after]
          schema:
            type: string
          description: |
            Cursor that points to the end of the page of data that has been returned.
        - schema:
            type: integer
          in: query
          name: page[size]
          description: Defines the maximum number of objects that may be returned.
  /notifications/v1/notifications/{id}:
    get:
      tags:
        - Notifications
      summary: Get notification by ID
      description: Gets a specific notification by its ID.
      operationId: get-notifications-v1-notifications-id
      security:
        - bearerAuth: []
      parameters:
        - $ref: "#/components/parameters/headerConformance"
        - name: id
          in: path
          schema:
            type: string
            example: ecd0e108a98e192af1d2c25055f4e3bed784b5c877204e73219a5203251feaab
          required: true
          description: |
            ID of the notification, sha3-256 hash of the serialized notification schema.
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Notification"
              examples:
                Success:
                  value:
                    schemaId: notification-001
                    type:
                      - Notification
                      - StoreVerifiableCredential
                    "@context":
                      - https://www.w3.org/2018/credentials/v1
                      - https://essif.europa.eu/schemas/vc/2020/v1
                      - https://essif.europa.eu/schemas/notifications/2020/v1
                    from: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
                    to: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ
                    issuanceDate: "2019-06-22T14:11:44Z"
                    expirationDate: "2019-06-27T14:11:44Z"
                    payload: {}
                    proof:
                      type: EcdsaSecp256k1Signature2019
                      created: "2019-11-17T14:00:00Z"
                      proofPurpose: assertionMethod
                      verificationMethod: did:ebsi:zub5ZZUfHLLptCduwEy8xRj#key-1
                      jws: eyJh..Iw
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Invalid {id} Parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: The {id} parameter is not valid
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Notification Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Not found:
                  value:
                    title: Not Found
                    status: 404
                    detail: Id parameter not found
        "500":
          description: Internal Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
    delete:
      tags:
        - Notifications
      summary: Delete notification by ID
      description: Deletes a notification by its ID.
      parameters:
        - $ref: "#/components/parameters/headerConformance"
        - name: id
          in: path
          schema:
            type: string
            example: ecd0e108a98e192af1d2c25055f4e3bed784b5c877204e73219a5203251feaab
          required: true
          description: |
            ID of the notification, sha3-256 hash of the serialized notification schema.
      operationId: delete-notifications-v1-notifications-id
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Notification deleted
        "400":
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Invalid {id} parameter:
                  value:
                    title: Bad Request
                    status: 400
                    detail: The {id} parameter is not valid
        "401":
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Unauthorized:
                  $ref: "#/components/examples/Unauthorized"
        "403":
          description: Forbidden
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Forbidden:
                  $ref: "#/components/examples/Forbidden"
        "404":
          description: Notification Not Found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Not found:
                  value:
                    title: Not Found
                    status: 404
                    detail: No notification found for the given ID
        "500":
          description: Internal Error
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/Problem"
              examples:
                Internal Server Error:
                  $ref: "#/components/examples/InternalError"
components:
  schemas:
    verifiableAttestation:
      title: EBSI Verifiable Attestation
      required:
        - "@context"
        - credentialSchema
        - credentialSubject
        - id
        - issuanceDate
        - issuer
        - proof
        - type
        - validFrom
      type: object
      properties:
        "@context":
          type: array
          description: Defines semantic context of the Verifiable Attestation.
          items:
            type: string
            format: uri
        id:
          type: string
          description: Defines unique identifier of the Verifiable Attestation.
        type:
          type: array
          description: Defines the Verifiable Credential type.
          items:
            type: string
        issuer:
          type: string
          description: Defines the issuer of the Verifiable Attestation.
        issuanceDate:
          type: string
          description: Defines when the Verifiable Attestation was issued.
          format: date-time
        validFrom:
          type: string
          description: |
            Defines the date and time, when the Verifiable Attestation becomes valid.
          format: date-time
        expirationDate:
          type: string
          description: Defines the date and time, when the Verifiable Attestation expires
          format: date-time
        credentialSubject:
          type: object
          properties: {}
          description: |
            Defines information about the subject that is described by the Verifiable Attestation.
        credentialStatus:
          required:
            - id
            - type
          type: object
          properties:
            id:
              type: string
              description: |
                References record in the Revocation and Endorsement Registry (RER) to enable
                verification of a Verifiable Attestation's validity.
            type:
              type: string
              description: Defines the Verifiable Credential status type.
          description: |
            Contains information about how to verify the status of the Verifiable Attestation (via
            the Revocation and Endorsement Registry, RER).
        credentialSchema:
          required:
            - id
            - type
          type: object
          properties:
            id:
              type: string
              description: |
                References the credential schema (template) stored on the (relevant) Trusted
                Schemas Registry (TSR) on which the Verifiable Attestation is based.
            type:
              type: string
              description: Defines credential schema type.
          description: |
            Contains information about the credential schema (template) on which the Verifiable
            Attestation is based.
        evidence:
          type: object
          properties:
            id:
              type: string
              description: |
                References the issuance policy stored on the (relevant) Trusted Schemas Registry
                (TSR) that has been followed for issuing the Verifiable Attestation.
            type:
              type: array
              description: Defines the evidence type
              items:
                type: string
            verifier:
              type: string
              description: |
                Defines entity which has verified documents before Verifiable Attestation issuance.
            evidenceDocument:
              type: array
              description: |
                Defines document(s) which have been verified before Verifiable Attestation
                issuance.
              items:
                type: string
            subjectPresence:
              type: string
              description: |
                Defines if the Verifiable Attestation subject was physically present in the course
                of the verification.
            documentPresence:
              type: array
              description: |
                Defines how the document(s) which have been verified before Verifiable Attestation
                issuance have been provided (e.g. physically, digitally).
              items:
                type: string
          description: |
            Contains information about the process which resulted in the issuance of the Verifiable
            Attestation.
        proof:
          required:
            - created
            - jws
            - proofPurpose
            - type
            - verificationMethod
          type: object
          properties:
            type:
              type: string
              description: Defines the proof type.
            proofPurpose:
              type: string
              description: Defines the purpose of the proof.
            created:
              type: string
              description: Defines the date and time, when the proof has been created.
              format: date-time
            verificationMethod:
              type: string
              description: |
                Contains information about the verification method / proof mechanisms.
            jws:
              type: string
              description: Defines the proof value in JWS format.
          description: Contains information about the proof.
      description: Schema of an EBSI Verifiable Attestation.
    verifiablePresentation:
      title: EBSI Verifiable Presentation
      description: Schema of an EBSI Verifiable Presentation
      type: object
      properties:
        "@context":
          description: Defines semantic context of the Verifiable Presentation.
          type: array
          items:
            type: string
            format: uri
        type:
          description: Defines the Verifiable Presentation type..
          type: array
          items:
            type: string
        holder:
          description: |
            Defines unique identifier of the party who shares the Verifiable Presentation.
          type: string
        verifiableCredential:
          description: Contains the personal information intended to be shared.
          type: object
        proof:
          description: Contains information about the proof.
          type: object
          properties:
            type:
              description: Defines the proof type.
              type: string
            proofPurpose:
              description: Defines the purpose of the proof.
              type: string
            created:
              description: Defines the date and time, when the proof has been created
              type: string
              format: date-time
            verificationMethod:
              description: |
                Contains information about the verification method / proof mechanisms.
              type: string
            challenge:
              description: |
                Defines a random or pseudo-random value used by some authentication protocols to
                mitigate replay attacks.
              type: string
            domain:
              description: |
                Defines a string value that specifies the operational domain of a digital proof.
              type: string
              format: hostname
            jws:
              description: Defines the proof value in JWS format.
              type: string
          required:
            - type
            - proofPurpose
            - created
            - verificationMethod
            - jws
      required:
        - "@context"
        - type
        - holder
        - verifiableCredential
        - proof
    verifiableAuthorisation:
      title: EBSI Verifiable Authorisation
      description: Schema of an EBSI Verifiable Authorisation
      type: object
      properties:
        "@context":
          description: Defines semantic context of the Verifiable Authorisation.
          type: array
          items:
            type: string
            format: uri
        id:
          description: Defines unique identifier of the Verifiable Authorisation.
          type: string
        type:
          description: Defines the Verifiable Credential type.
          type: array
          items:
            type: string
        issuer:
          description: Defines the issuer of the Verifiable Authorisation.
          type: string
        issuanceDate:
          description: Defines when the Verifiable Authorisation was issued.
          type: string
          format: date-time
        validFrom:
          description: |
            Defines the date and time, when the Verifiable Authorisation becomes valid.
          type: string
          format: date-time
        expirationDate:
          description: Defines the date and time, when the Verifiable Authorisation expires.
          type: string
          format: date-time
        credentialSubject:
          description: |
            Defines information about the subject that is described by the Verifiable Authorisation.
          type: object
          properties:
            id:
              description: DID of the subject
              type: string
          required:
            - id
        credentialStatus:
          description: |
            Contains information about how to verify the status of the Verifiable Authorisation
            (via the Revocation and Endorsement Registry, RER).
          type: object
          properties:
            id:
              description: |
                References record in the Revocation and Endorsement Registry (RER) to enable
                verification of a Verifiable Authorisation’s validity.
              type: string
            type:
              description: Defines the Verifiable Credential status type.
              type: string
          required:
            - id
            - type
        credentialSchema:
          description: |
            Contains information about the credential schema (template) on which the Verifiable
            Authorisation is based.
          type: object
          properties:
            id:
              description: |
                References the credential schema (template) stored on the (relevant) Trusted
                Schemas Registry (TSR) on which the Verifiable Authorisation is based.
              type: string
            type:
              description: Defines credential schema type.
              type: string
          required:
            - id
            - type
        evidence:
          description: |
            Contains information about the process which resulted in the issuance of the Verifiable
            Authorisation.
          type: object
          properties:
            id:
              description: |
                References the issuance policy stored on the (relevant) Trusted Schemas Registry
                (TSR) that has been followed for issuing the Verifiable Authorisation.
              type: string
            type:
              description: Defines the evidence type.
              type: array
              items:
                type: string
        proof:
          description: Contains information about the proof.
          type: object
          properties:
            type:
              description: Defines the proof type.
              type: string
            proofPurpose:
              description: Defines the purpose of the proof.
              type: string
            created:
              description: Defines the date and time, when the proof has been created.
              type: string
              format: date-time
            verificationMethod:
              description: |
                Contains information about the verification method / proof mechanisms.
              type: string
            jws:
              description: Defines the proof value in JWS format.
              type: string
          required:
            - type
            - proofPurpose
            - created
            - verificationMethod
            - jws
      required:
        - "@context"
        - id
        - type
        - issuer
        - issuanceDate
        - validFrom
        - credentialSubject
        - credentialSchema
        - proof
    Notification:
      type: object
      description: Notification
      example:
        schemaId: notification-001
        type:
          - Notification
          - StoreVerifiableCredential
        "@context":
          - https://www.w3.org/2018/credentials/v1
          - https://essif.europa.eu/schemas/vc/2020/v1
          - https://essif.europa.eu/schemas/notifications/2020/v1
        from: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
        to: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ
        issuanceDate: "2019-06-22T14:11:44Z"
        expirationDate: "2019-06-27T14:11:44Z"
        payload: {}
        proof:
          type: EcdsaSecp256k1Signature2019
          created: "2019-11-17T14:00:00Z"
          proofPurpose: assertionMethod
          verificationMethod: did:ebsi:zub5ZZUfHLLptCduwEy8xRj#key-1
          jws: eyJh..Iw
      title: Notification
      properties:
        schemaId:
          type: string
          description: |
            Notification Schema identifier generated after registering it to the Trusted Schemas
            Registry.
          example: notification-001
        type:
          type: array
          description: |
            Notification type that corresponds to the Notifications type that is included as data.
          example:
            - Notification
            - StoreVerifiableCredential
          uniqueItems: true
          items:
            type: string
        "@context":
          description: |
            An ordered set where the first item is a URI https://www.w3.org/2018/credentials/v1. It
            is used to define terms and help to express specific identifiers in a compact manner.
          items:
            type: string
          uniqueItems: true
          example:
            - https://www.w3.org/2018/credentials/v1
          type: array
        from:
          type: string
          description: Sender's Decentralized Identifier
          example: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
        to:
          type: string
          description: Recipient's Decentralized Identifier
          example: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ
        issuanceDate:
          type: string
          description: |
            Date and time at which the information associated with the notification becomes valid.
          format: date-time
          example: "2010-01-01T19:23:24Z"
        expirationDate:
          type: string
          format: date-time
          example: "2020-01-01T19:23:24Z"
          description: Date and time at which a notification ceases to be valid.
        payload:
          type: object
          format: application/json
          description: "Any valid JSON. Size limit: 1MB"
          example: "{}"
        proof:
          $ref: "#/components/schemas/embeddedProof"
      required:
        - schemaId
        - type
        - "@context"
        - from
        - to
        - issuanceDate
        - payload
        - proof
    embeddedProof:
      title: Embedded Proof
      type: object
      description: |
        Cryptographic proofs that can be used to detect tampering and verify the authorship of a
        notification. An embedded proof is a mechanism where the proof is included in the data,
        such as a Linked Data Signature.
      properties:
        type:
          type: string
          description: Type of the object or the datatype of the typed value.
          example: EcdsaSecp256k1Signature2019
        created:
          type: string
          description: Date and time at which proof has been created.
          format: date-time
          example: "2019-11-17T09:00:00Z"
        proofPurpose:
          type: string
          description: |
            It expresses the purpose of the proof and ensures the information is protected by the
            signature.
          example: assertionMethod
        verificationMethod:
          type: string
          description: |
            Specifies the public key that can be used to verify the digital signature.

            Dereferencing a public key URL reveals information about the controller of the key,
            which can be checked against the issuer of the credential.
          example: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ#key-1
        jws:
          type: string
          description: JSON Web Signature
          example: eyJhbGciOiJFUzI1NksifQ.eyJzdWIiOiJFQlNJIDIwMTkifQ.oggE3ft3kJYPGGa9eBibpbjgeJXw4fLbVMouVoM2NfcDxsl_UUUIarsS1VpBoYEs7s9cBlc4uC0EbnJCHfVJIw
      required:
        - type
        - created
        - proofPurpose
        - verificationMethod
        - jws
      example:
        type: RsaSignature2018
        created: "2018-06-18T21:19:10Z"
        proofPurpose: assertionMethod
        verificationMethod: https://example.com/jdoe/keys/1
        jws: eyJhbGciOiJQUzI1NiIsImI2NCI..
    Problem:
      description: A Problem Details object (RFC 7807)
      type: object
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide
            human-readable documentation for the problem type.
          default: about:blank
        title:
          type: string
          description: |
            A short summary of the problem type.
          example: Internal Server Error
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence of the problem.
          minimum: 400
          maximum: 600
          example: 500
        detail:
          type: string
          description: |
            A human readable explanation specific to this occurrence of the problem.
          example: Connection timeout
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem. It may or may
            not yield further information if dereferenced.
    Links:
      title: Links
      type: object
      properties:
        last:
          type: string
          description: URI of the last page
        prev:
          type: string
          description: URI of the previous page
        next:
          type: string
          description: URI of the next page
        first:
          type: string
          description: URI of the first page
      description: links model used for pagination
      example:
        first: https://api.ebsi.xyz/notifications/v1/notifications?page[after]=1&page[size]=2
        prev: https://api.ebsi.xyz/notifications/v1/notifications?page[after]=2&page[size]=2
        next: https://api.ebsi.xyz/notifications/v1/notifications?page[after]=4&page[size]=2
        last: https://api.ebsi.xyz/notifications/v1/notifications?page[after]=7&page[size]=2
    NotificationLinks:
      type: object
      description: Notification Object with a link to retrieve the specific notification.
      example:
        schemaId: notification-001
        type:
          - Notification
          - StoreVerifiableCredential
        "@context":
          - https://www.w3.org/2018/credentials/v1
          - https://essif.europa.eu/schemas/vc/2020/v1
          - https://essif.europa.eu/schemas/notifications/2020/v1
        from: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
        to: did:ebsi:znbuGDt6tEqpGZNAuGc2uvZ
        issuanceDate: "2019-06-22T14:11:44Z"
        expirationDate: "2019-06-27T14:11:44Z"
        payload: {}
        proof:
          type: EcdsaSecp256k1Signature2019
          created: "2019-11-17T14:00:00Z"
          proofPurpose: assertionMethod
          verificationMethod: did:ebsi:zub5ZZUfHLLptCduwEy8xRj#key-1
          jws: eyJh..Iw
        _links:
          self:
            href: https://api.ebsi.xyz/notifications/v1/notifications/123
      title: NotificationLinks
      properties:
        schemaId:
          type: string
          description: |
            Notification Schema identifier generated after registering it to the Trusted Schemas
            Registry.
          example: notification-001
        type:
          type: array
          description: |
            Notification type that corresponds to the Notifications type that is included as data.
          example:
            - Notification
            - StoreVerifiableCredential
          uniqueItems: true
          items:
            type: string
        "@context":
          description: |
            An ordered set where the first item is a URI https://www.w3.org/2018/credentials/v1. It
            is used to define terms and help to express specific identifiers in a compact manner.
          items:
            type: string
          uniqueItems: true
          example:
            - https://www.w3.org/2018/credentials/v1
          type: array
        from:
          type: string
          description: Sender's Decentralized Identifier
          example: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
        to:
          type: string
          description: Recipient's Decentralized Identifier
          example: did:ebsi:zub5ZZUfHLLptCduwEy8xRj
        issuanceDate:
          type: string
          description: |
            Date and time at which the information associated with the notification becomes valid.
          format: date-time
          example: "2010-01-01T19:23:24Z"
        expirationDate:
          type: string
          format: date-time
          example: "2020-01-01T19:23:24Z"
          description: Date and time at which a notification ceases to be valid.
        payload:
          type: object
          format: application/json
          description: "Any valid JSON. Size limit: 1MB"
        proof:
          $ref: "#/components/schemas/embeddedProof"
        _links:
          $ref: "#/components/schemas/_links"
      required:
        - schemaId
        - type
        - "@context"
        - from
        - to
        - issuanceDate
        - payload
        - proof
        - _links
    _links:
      title: _links
      type: object
      properties:
        self:
          type: object
          properties:
            href:
              type: string
              description: URI to the specific notification with its id
              example: https://api.ebsi.xyz/notifications/v1/notifications/123
          required:
            - href
      required:
        - self
  examples:
    BadRequest:
      value:
        title: Bad Request
        status: 400
        detail: Bad request.
    Forbidden:
      value:
        title: Forbidden
        status: 403
        detail: Forbidden.
    Unauthorized:
      value:
        title: Unauthorized
        status: 401
        detail: You are not authorized to access the resources.
    InternalError:
      value:
        title: Internal Server Error
        status: 500
        detail: |
          The server encountered an internal error and was unable to complete your request.
  parameters:
    headerConformance:
      in: header
      name: Conformance
      description: |
        The header MUST be used ONLY for the EBSI conformance testing.
        - Type: string
        - Format: UUID V4

        The header is used to log the activities.
      required: false
      schema:
        type: string
        format: uuid
      example: edb60e02-398d-4b62-8028-85710b2476a5
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
